export const PACKAGES = [
  {
    id: 'classic-darjeeling',
    slug: 'classic-darjeeling-explorer',
    title: 'Classic Darjeeling Explorer',
    destination: 'Darjeeling, West Bengal',
    category: 'darjeeling',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Best Seller',
    badgeColor: 'red',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1570789210967-2cac24afeb00?w=800&q=80',
    ],
    description:
      "Experience the Queen of the Hills at its finest. Witness sunrise over Kanchenjunga from Tiger Hill, ride the UNESCO-listed Toy Train, and wander through aromatic tea estates.",
    highlights: ['Tiger Hill Sunrise', 'Darjeeling Toy Train', 'Tea Garden Walk', 'Batasia Loop', 'Himalayan Zoo'],
    tags: ['Nature', 'Heritage', 'Tea'],
    location: { lat: 27.036, lng: 88.2627, mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival and Mall Road', desc: 'Pickup from NJP or Bagdogra, scenic drive to Darjeeling, check-in, and evening at Chowrasta.' },
      { day: 'Day 2', title: 'Tiger Hill and Town', desc: 'Pre-dawn Tiger Hill visit, then Batasia Loop, Ghum Monastery, and the Himalayan Zoo.' },
      { day: 'Day 3', title: 'Tea Gardens and Culture', desc: 'Visit Happy Valley Tea Estate, the Tibetan Refugee Centre, and local shopping streets.' },
      { day: 'Day 4', title: 'Toy Train and Departure', desc: 'Toy Train joyride, breakfast, and transfer back to NJP.' },
    ],
    inclusions: ['3 nights hotel stay', 'Daily breakfast and dinner', 'All cab transfers', 'Tiger Hill jeep', 'Tea garden entry', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Personal expenses', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'gangtok-sikkim',
    slug: 'gangtok-rumtek-monastery',
    title: 'Gangtok and Rumtek Monastery',
    destination: 'Gangtok, Sikkim',
    category: 'sikkim',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Popular',
    badgeColor: 'blue',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80'],
    description:
      'Discover the lively capital of Sikkim, where ancient monasteries, markets, and Himalayan viewpoints come together in one memorable escape.',
    highlights: ['Rumtek Monastery', 'Gangtok Cable Car', 'MG Marg', 'Tashi Viewpoint', 'Banjhakri Falls'],
    tags: ['Spiritual', 'Nature', 'Culture'],
    location: { lat: 27.3389, lng: 88.6065, mapUrl: 'https://maps.google.com/?q=Gangtok,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Gangtok', desc: 'NJP pickup, scenic NH-10 drive, hotel check-in, and evening walk on MG Marg.' },
      { day: 'Day 2', title: 'Monasteries and Views', desc: 'Rumtek Monastery, Tashi Viewpoint, Banjhakri Falls, and the Institute of Tibetology.' },
      { day: 'Day 3', title: 'Cable Car and Markets', desc: 'Morning ropeway ride, Enchey Monastery visit, and shopping for local crafts.' },
      { day: 'Day 4', title: 'Departure', desc: 'Breakfast and transfer back to NJP.' },
    ],
    inclusions: ['3 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Cable car ticket', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Entry fees', 'Personal shopping'],
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'grand-himalaya',
    slug: 'grand-eastern-himalaya-tour',
    title: 'Grand Eastern Himalaya Tour',
    destination: 'Darjeeling + Kalimpong + Sikkim',
    category: 'combo',
    nights: 6,
    days: 7,
    minPax: 2,
    badge: 'Best Value',
    badgeColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80'],
    description:
      'A week-long circuit through tea gardens, monasteries, mountain roads, and high-altitude lakes across the Eastern Himalayas.',
    highlights: ['Tea Gardens', 'Toy Train', 'Tsomgo Lake', 'Rumtek Monastery', 'Kalimpong Views'],
    tags: ['Multi-Destination', 'Heritage', 'Adventure'],
    location: { lat: 27.2, lng: 88.5, mapUrl: 'https://maps.google.com/?q=Darjeeling+Sikkim' },
    itinerary: [
      { day: 'Day 1-2', title: 'Darjeeling Highlights', desc: 'Tiger Hill sunrise, tea garden walk, and Toy Train joyride.' },
      { day: 'Day 3', title: 'Kalimpong', desc: 'Zong Dog Palri Monastery, Deolo Hill, and flower nurseries.' },
      { day: 'Day 4-5', title: 'Gangtok', desc: 'Rumtek, Tashi Viewpoint, cable car ride, and MG Marg.' },
      { day: 'Day 6', title: 'Tsomgo Lake', desc: 'Day trip to the high-altitude lake with permits arranged.' },
      { day: 'Day 7', title: 'Departure', desc: 'Return to NJP.' },
    ],
    inclusions: ['6 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Permits', 'Sightseeing', 'Guide'],
    exclusions: ['Flights or trains', 'Lunch', 'Optional rides', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'dooars-wildlife',
    slug: 'dooars-wild-jungle-safari',
    title: 'Dooars Wild Jungle Safari',
    destination: 'Dooars, West Bengal',
    category: 'dooars',
    nights: 3,
    days: 4,
    minPax: 4,
    badge: 'Wildlife',
    badgeColor: 'green',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80'],
    description:
      'Explore the forests of North Bengal with jeep safaris, birdwatching, and chances to spot rhinos, elephants, and gaur.',
    highlights: ['Rhino Safari', 'Elephant Safari', 'Gorumara', 'Jaldapara', 'Chilapata Forest'],
    tags: ['Wildlife', 'Nature', 'Safari'],
    location: { lat: 26.75, lng: 89.16, mapUrl: 'https://maps.google.com/?q=Dooars,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Siliguri to Dooars', desc: 'Transfer to eco-resort and evening nature walk.' },
      { day: 'Day 2', title: 'Gorumara Safari', desc: 'Morning jeep safari and sunset watchtower visit.' },
      { day: 'Day 3', title: 'Jaldapara', desc: 'Elephant safari and wildlife spotting.' },
      { day: 'Day 4', title: 'Departure', desc: 'Forest drive and return to NJP.' },
    ],
    inclusions: ['3 nights resort stay', 'Safaris', 'Park permits', 'Naturalist guide'],
    exclusions: ['Air or train tickets', 'Alcohol', 'Tips', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'pelling-honeymoon',
    slug: 'pelling-romantic-getaway',
    title: 'Pelling Romantic Getaway',
    destination: 'Pelling, West Sikkim',
    category: 'honeymoon',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Honeymoon',
    badgeColor: 'pink',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    description:
      'A romantic mountain retreat with sweeping Kanchenjunga views, monasteries, waterfalls, and special honeymoon touches.',
    highlights: ['View Room', 'Glass Skywalk', 'Pemayangtse Monastery', 'Waterfalls', 'Candlelight Dinner'],
    tags: ['Romantic', 'Mountains', 'Honeymoon'],
    location: { lat: 27.35, lng: 88.2167, mapUrl: 'https://maps.google.com/?q=Pelling,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Pickup, transfer to Pelling, and welcome dinner.' },
      { day: 'Day 2', title: 'Monastery Trail', desc: 'Pemayangtse Monastery, Rabdentse ruins, and heritage viewpoints.' },
      { day: 'Day 3', title: 'Skywalk and Waterfalls', desc: 'Glass sky bridge and waterfall excursion.' },
      { day: 'Day 4', title: 'Lake and Leisure', desc: 'Khecheopalri Lake visit and relaxed afternoon.' },
      { day: 'Day 5', title: 'Departure', desc: 'Breakfast and transfer back.' },
    ],
    inclusions: ['4 nights resort stay', 'Daily breakfast and dinner', 'Special honeymoon arrangements', 'Transfers'],
    exclusions: ['Air or train tickets', 'Lunch', 'Extra spa sessions', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'kalimpong',
    slug: 'kalimpong-flower-valley',
    title: 'Kalimpong Flower Valley',
    destination: 'Kalimpong, West Bengal',
    category: 'kalimpong',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Hidden Gem',
    badgeColor: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    gallery: [],
    description:
      'A compact hill retreat known for nurseries, monasteries, Teesta valley viewpoints, and a quieter pace than the busier hill stations.',
    highlights: ['Flower Nurseries', 'Deolo Hill', 'Monasteries', 'Teesta Views', 'Arts and Crafts'],
    tags: ['Nature', 'Culture', 'Offbeat'],
    location: { lat: 27.066, lng: 88.468, mapUrl: 'https://maps.google.com/?q=Kalimpong,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Transfer from NJP and local market stroll.' },
      { day: 'Day 2', title: 'Views and Monasteries', desc: 'Deolo Hill, monasteries, and nursery visits.' },
      { day: 'Day 3', title: 'Departure', desc: 'Arts and crafts centre visit before return.' },
    ],
    inclusions: ['2 nights hotel stay', 'Daily breakfast', 'Transfers', 'Guide'],
    exclusions: ['Air or train tickets', 'Some meals', 'Entry fees'],
    isFeatured: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'sandakphu-trek',
    slug: 'sandakphu-trek',
    title: 'Sandakphu Summit Trek',
    destination: 'Sandakphu, West Bengal',
    category: 'trek',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Adventure',
    badgeColor: 'orange',
    imageUrl: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80'],
    description:
      "A bucket-list trek with ridgeline views of Everest, Kanchenjunga, Lhotse, and Makalu on clear mornings.",
    highlights: ['High-altitude views', 'Singalila trails', 'Tumling', 'Kalapokhri', 'Summit sunrise'],
    tags: ['Trek', 'Adventure', 'Summit'],
    location: { lat: 27.1054, lng: 87.848, mapUrl: 'https://maps.google.com/?q=Sandakphu,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Maneybhanjang to Tumling', desc: 'Trek through Singalila National Park.' },
      { day: 'Day 2', title: 'Tumling to Kalapokhri', desc: 'Ridge walk with Himalayan views.' },
      { day: 'Day 3', title: 'Summit Day', desc: 'Climb to Sandakphu and watch the sunrise panorama.' },
      { day: 'Day 4', title: 'Descent', desc: 'Forest descent and overnight stay.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to base and transfer to Siliguri.' },
    ],
    inclusions: ['Stay on trek', 'Meals on trek', 'Guide', 'Porter', 'Permits', 'First aid'],
    exclusions: ['Transport to Siliguri', 'Gear rental', 'Insurance'],
    isFeatured: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'lachung-yumthang',
    slug: 'lachung-yumthang-valley',
    title: 'Lachung and Yumthang Valley',
    destination: 'North Sikkim',
    category: 'sikkim',
    nights: 4,
    days: 5,
    minPax: 4,
    badge: 'Seasonal',
    badgeColor: 'teal',
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    gallery: [],
    description:
      'A scenic North Sikkim journey through alpine valleys, rivers, seasonal flowers, and mountain villages.',
    highlights: ['Yumthang Valley', 'Zero Point', 'Lachung Village', 'Rhododendrons', 'Glacial streams'],
    tags: ['Valley', 'Flowers', 'North Sikkim'],
    location: { lat: 27.8167, lng: 88.7167, mapUrl: 'https://maps.google.com/?q=Yumthang+Valley,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Gangtok to Lachung', desc: 'Drive through river valleys and mountain roads.' },
      { day: 'Day 2', title: 'Yumthang and Zero Point', desc: 'Visit the valley and optional Zero Point excursion.' },
      { day: 'Day 3', title: 'Village Exploration', desc: 'Discover local culture and monastery life.' },
      { day: 'Day 4', title: 'Return to Gangtok', desc: 'Scenic drive back.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer toward NJP or Siliguri.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast and dinner', 'Permits', 'Transfers', 'Guide'],
    exclusions: ['Optional excursions', 'Lunch', 'Personal expenses', 'Insurance'],
    isFeatured: false,
    isActive: true,
    sortOrder: 8,
  },
]

export const DESTINATIONS = [
  { id: 'darjeeling', name: 'Darjeeling', region: 'West Bengal', pkgCount: 12, imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' } },
  { id: 'sikkim', name: 'Sikkim', region: 'North-East India', pkgCount: 9, imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Sikkim' } },
  { id: 'dooars', name: 'Dooars', region: 'West Bengal', pkgCount: 6, imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Dooars,West+Bengal' } },
  { id: 'kalimpong', name: 'Kalimpong', region: 'West Bengal', pkgCount: 5, imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Kalimpong,West+Bengal' } },
  { id: 'pelling', name: 'Pelling', region: 'West Sikkim', pkgCount: 4, imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Pelling,Sikkim' } },
  { id: 'sandakphu', name: 'Sandakphu', region: 'West Bengal', pkgCount: 3, imageUrl: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=600&q=80', location: { mapUrl: 'https://maps.google.com/?q=Sandakphu,West+Bengal' } },
]

export const TESTIMONIALS = [
  { id: 1, authorName: 'Ananya Bose', authorFrom: 'Kolkata', tripName: 'Darjeeling Tour', rating: 5, reviewText: 'The sunrise at Tiger Hill left us speechless. Everything was coordinated beautifully and the trip felt effortless from start to finish.', avatarChar: 'A' },
  { id: 2, authorName: 'Rahul Mehta', authorFrom: 'Mumbai', tripName: 'Sikkim Family Tour', rating: 5, reviewText: 'The family trip exceeded expectations. Great pacing, very dependable transport, and genuine local knowledge throughout.', avatarChar: 'R' },
  { id: 3, authorName: 'Priya and Vikram', authorFrom: 'Delhi', tripName: 'Pelling Honeymoon', rating: 5, reviewText: 'The views, stays, and thoughtful planning made our honeymoon unforgettable. We felt taken care of the whole time.', avatarChar: 'P' },
  { id: 4, authorName: 'Suresh Nair', authorFrom: 'Bangalore', tripName: 'Dooars Wildlife Tour', rating: 5, reviewText: 'Saw rhinos, elephants, and so much birdlife. The team was professional, punctual, and easy to coordinate with.', avatarChar: 'S' },
  { id: 5, authorName: 'Karan Thakur', authorFrom: 'Pune', tripName: 'Sandakphu Trek', rating: 5, reviewText: 'One of the most rewarding treks I have done. The guide support and route planning were excellent.', avatarChar: 'K' },
]

export const CATEGORIES = [
  { id: 'all', label: 'All Packages', icon: 'All' },
  { id: 'darjeeling', label: 'Darjeeling', icon: 'Tea' },
  { id: 'sikkim', label: 'Sikkim', icon: 'Peak' },
  { id: 'dooars', label: 'Dooars', icon: 'Wild' },
  { id: 'kalimpong', label: 'Kalimpong', icon: 'Bloom' },
  { id: 'honeymoon', label: 'Honeymoon', icon: 'Love' },
  { id: 'trek', label: 'Treks', icon: 'Trail' },
  { id: 'combo', label: 'Combo Tours', icon: 'Mix' },
]
