import ladakhImage from '../assets/destinations/ladakh.svg'
import ladakhThikseyMonastery from '../assets/gallery/ladakh/thiksey-monastery.png'
import ladakhNubraCamelSafari from '../assets/gallery/ladakh/nubra-valley-camel-safari.png'
import ladakhPangongLake from '../assets/gallery/ladakh/pangong-lake-cairns.png'
import ladakhHikkimVillage from '../assets/gallery/ladakh/hikkim-last-village.png'
import ladakhNubraValleyRiver from '../assets/gallery/ladakh/nubra-valley-river.jpg'
import jammuKashmirImage from '../assets/destinations/jammu-kashmir.png'
import himachalImage from '../assets/destinations/himachal.png'
import uttarakhandImage from '../assets/destinations/uttarakhand.png'
import darjeelingImage from '../assets/destinations/darjeeling.png'
import sikkimImage from '../assets/destinations/sikkim.png'
import arunachalImage from '../assets/destinations/arunachal.png'
import assamImage from '../assets/destinations/assam.png'
import meghalayaImage from '../assets/destinations/meghalaya.png'
import keralaImage from '../assets/destinations/kerala.png'
import nepalImage from '../assets/destinations/nepal.png'
import bhutanImage from '../assets/destinations/bhutan.png'
import { getPackageGallery, getPackageCover } from './galleryLoader'

export const PACKAGES = [
  {
    id: 'classic-darjeeling',
    slug: 'classic-darjeeling-explorer',
    title: 'Classic Darjeeling Explorer',
    destination: 'Darjeeling, West Bengal',
    states: ['Darjeeling'],
    category: 'darjeeling',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Best Seller',
    badgeColor: 'red',
    imageUrl: getPackageCover('classic-darjeeling') || 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    gallery: [...getPackageGallery('classic-darjeeling'),
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1570789210967-2cac24afeb00?w=800&q=80',
    ],
    description:
      "Experience the Queen of the Hills at its finest. Witness sunrise over Kanchenjunga from Tiger Hill, ride the UNESCO-listed Toy Train, and wander through aromatic tea estates.",
    highlights: ['Tiger Hill Sunrise', 'Darjeeling Toy Train', 'Tea Garden Walk', 'Batasia Loop', 'Himalayan Zoo'],
    tags: ['Nature', 'Heritage', 'Tea'],
    location: { lat: 27.036, lng: 88.2627, mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival and Mall Road', desc: 'Pickup from NJP or Bagdogra, scenic drive to Darjeeling, check-in, and evening at Chowrasta.' },
      { day: 'Day 2', title: 'Tiger Hill and Town', desc: 'Pre-dawn Tiger Hill visit, then Batasia Loop, Ghum Monastery, and the Himalayan Zoo.' },
      { day: 'Day 3', title: 'Tea Gardens and Culture', desc: 'Visit Happy Valley Tea Estate, the Tibetan Refugee Centre, and local shopping streets.' },
      { day: 'Day 4', title: 'Toy Train and Departure', desc: 'Toy Train joyride, breakfast, and transfer back to NJP.' },
    ],
    inclusions: ['3 nights hotel stay', 'Daily breakfast and dinner', 'All cab transfers', 'Tiger Hill jeep', 'Tea garden entry', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Personal expenses', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'gangtok-sikkim',
    slug: 'gangtok-rumtek-monastery',
    title: 'Gangtok and Rumtek Monastery',
    destination: 'Gangtok, Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Popular',
    badgeColor: 'blue',
    imageUrl: getPackageCover('gangtok-sikkim') || 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    gallery: [...getPackageGallery('gangtok-sikkim'), 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80'],
    description:
      'Discover the lively capital of Sikkim, where ancient monasteries, markets, and Himalayan viewpoints come together in one memorable escape.',
    highlights: ['Rumtek Monastery', 'Gangtok Cable Car', 'MG Marg', 'Tashi Viewpoint', 'Banjhakri Falls'],
    tags: ['Spiritual', 'Nature', 'Culture'],
    location: { lat: 27.3389, lng: 88.6065, mapUrl: 'https://maps.google.com/?q=Gangtok,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Gangtok', desc: 'NJP pickup, scenic NH-10 drive, hotel check-in, and evening walk on MG Marg.' },
      { day: 'Day 2', title: 'Monasteries and Views', desc: 'Rumtek Monastery, Tashi Viewpoint, Banjhakri Falls, and the Institute of Tibetology.' },
      { day: 'Day 3', title: 'Cable Car and Markets', desc: 'Morning ropeway ride, Enchey Monastery visit, and shopping for local crafts.' },
      { day: 'Day 4', title: 'Departure', desc: 'Breakfast and transfer back to NJP.' },
    ],
    inclusions: ['3 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Cable car ticket', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Entry fees', 'Personal shopping'],
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'grand-himalaya',
    slug: 'grand-eastern-himalaya-tour',
    title: 'Grand Eastern Himalaya Tour',
    destination: 'Darjeeling + Kalimpong + Sikkim',
    states: ['Darjeeling', 'Sikkim'],
    category: 'combo',
    nights: 6,
    days: 7,
    minPax: 2,
    badge: 'Best Value',
    badgeColor: 'amber',
    imageUrl: getPackageCover('grand-himalaya') || 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    gallery: [...getPackageGallery('grand-himalaya'), 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80'],
    description:
      'A week-long circuit through tea gardens, monasteries, mountain roads, and high-altitude lakes across the Eastern Himalayas.',
    highlights: ['Tea Gardens', 'Toy Train', 'Tsomgo Lake', 'Rumtek Monastery', 'Kalimpong Views'],
    tags: ['Multi-Destination', 'Heritage', 'Adventure'],
    location: { lat: 27.2, lng: 88.5, mapUrl: 'https://maps.google.com/?q=Darjeeling+Sikkim' },
    itinerary: [
      { day: 'Day 1-2', title: 'Darjeeling Highlights', desc: 'Tiger Hill sunrise, tea garden walk, and Toy Train joyride.' },
      { day: 'Day 3', title: 'Kalimpong', desc: 'Zong Dog Palri Monastery, Deolo Hill, and flower nurseries.' },
      { day: 'Day 4-5', title: 'Gangtok', desc: 'Rumtek, Tashi Viewpoint, cable car ride, and MG Marg.' },
      { day: 'Day 6', title: 'Tsomgo Lake', desc: 'Day trip to the high-altitude lake with permits arranged.' },
      { day: 'Day 7', title: 'Departure', desc: 'Return to NJP.' },
    ],
    inclusions: ['6 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Permits', 'Sightseeing', 'Guide'],
    exclusions: ['Flights or trains', 'Lunch', 'Optional rides', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'dooars-wildlife',
    slug: 'dooars-wild-jungle-safari',
    title: 'Dooars Wild Jungle Safari',
    destination: 'Dooars, West Bengal',
    states: ['Darjeeling'],
    category: 'dooars',
    nights: 3,
    days: 4,
    minPax: 4,
    badge: 'Wildlife',
    badgeColor: 'green',
    imageUrl: getPackageCover('dooars-wildlife') || 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    gallery: [...getPackageGallery('dooars-wildlife'), 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80'],
    description:
      'Explore the forests of North Bengal with jeep safaris, birdwatching, and chances to spot rhinos, elephants, and gaur.',
    highlights: ['Rhino Safari', 'Elephant Safari', 'Gorumara', 'Jaldapara', 'Chilapata Forest'],
    tags: ['Wildlife', 'Nature', 'Safari'],
    location: { lat: 26.75, lng: 89.16, mapUrl: 'https://maps.google.com/?q=Dooars,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Siliguri to Dooars', desc: 'Transfer to eco-resort and evening nature walk.' },
      { day: 'Day 2', title: 'Gorumara Safari', desc: 'Morning jeep safari and sunset watchtower visit.' },
      { day: 'Day 3', title: 'Jaldapara', desc: 'Elephant safari and wildlife spotting.' },
      { day: 'Day 4', title: 'Departure', desc: 'Forest drive and return to NJP.' },
    ],
    inclusions: ['3 nights resort stay', 'Safaris', 'Park permits', 'Naturalist guide'],
    exclusions: ['Air or train tickets', 'Alcohol', 'Tips', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'pelling-honeymoon',
    slug: 'pelling-romantic-getaway',
    title: 'Pelling Romantic Getaway',
    destination: 'Pelling, West Sikkim',
    states: ['Sikkim'],
    category: 'honeymoon',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Honeymoon',
    badgeColor: 'pink',
    imageUrl: getPackageCover('pelling-honeymoon') || 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    gallery: [...getPackageGallery('pelling-honeymoon'), 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    description:
      'A romantic mountain retreat with sweeping Kanchenjunga views, monasteries, waterfalls, and special honeymoon touches.',
    highlights: ['View Room', 'Glass Skywalk', 'Pemayangtse Monastery', 'Waterfalls', 'Candlelight Dinner'],
    tags: ['Romantic', 'Mountains', 'Honeymoon'],
    location: { lat: 27.35, lng: 88.2167, mapUrl: 'https://maps.google.com/?q=Pelling,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Pickup, transfer to Pelling, and welcome dinner.' },
      { day: 'Day 2', title: 'Monastery Trail', desc: 'Pemayangtse Monastery, Rabdentse ruins, and heritage viewpoints.' },
      { day: 'Day 3', title: 'Skywalk and Waterfalls', desc: 'Glass sky bridge and waterfall excursion.' },
      { day: 'Day 4', title: 'Lake and Leisure', desc: 'Khecheopalri Lake visit and relaxed afternoon.' },
      { day: 'Day 5', title: 'Departure', desc: 'Breakfast and transfer back.' },
    ],
    inclusions: ['4 nights resort stay', 'Daily breakfast and dinner', 'Special honeymoon arrangements', 'Transfers'],
    exclusions: ['Air or train tickets', 'Lunch', 'Extra spa sessions', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'kalimpong',
    slug: 'kalimpong-flower-valley',
    title: 'Kalimpong Flower Valley',
    destination: 'Kalimpong, West Bengal',
    states: ['Darjeeling'],
    category: 'kalimpong',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Hidden Gem',
    badgeColor: 'purple',
    imageUrl: getPackageCover('kalimpong') || 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    gallery: getPackageGallery('kalimpong'),
    description:
      'A compact hill retreat known for nurseries, monasteries, Teesta valley viewpoints, and a quieter pace than the busier hill stations.',
    highlights: ['Flower Nurseries', 'Deolo Hill', 'Monasteries', 'Teesta Views', 'Arts and Crafts'],
    tags: ['Nature', 'Culture', 'Offbeat'],
    location: { lat: 27.066, lng: 88.468, mapUrl: 'https://maps.google.com/?q=Kalimpong,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Transfer from NJP and local market stroll.' },
      { day: 'Day 2', title: 'Views and Monasteries', desc: 'Deolo Hill, monasteries, and nursery visits.' },
      { day: 'Day 3', title: 'Departure', desc: 'Arts and crafts centre visit before return.' },
    ],
    inclusions: ['2 nights hotel stay', 'Daily breakfast', 'Transfers', 'Guide'],
    exclusions: ['Air or train tickets', 'Some meals', 'Entry fees'],
    isFeatured: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'sandakphu-trek',
    slug: 'sandakphu-trek',
    title: 'Sandakphu Summit Trek',
    destination: 'Sandakphu, West Bengal',
    states: ['Darjeeling'],
    category: 'trek',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Adventure',
    badgeColor: 'orange',
    imageUrl: getPackageCover('sandakphu-trek') || 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&q=80',
    gallery: [...getPackageGallery('sandakphu-trek'), 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80'],
    description:
      "A bucket-list trek with ridgeline views of Everest, Kanchenjunga, Lhotse, and Makalu on clear mornings.",
    highlights: ['High-altitude views', 'Singalila trails', 'Tumling', 'Kalapokhri', 'Summit sunrise'],
    tags: ['Trek', 'Adventure', 'Summit'],
    location: { lat: 27.1054, lng: 87.848, mapUrl: 'https://maps.google.com/?q=Sandakphu,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Maneybhanjang to Tumling', desc: 'Trek through Singalila National Park.' },
      { day: 'Day 2', title: 'Tumling to Kalapokhri', desc: 'Ridge walk with Himalayan views.' },
      { day: 'Day 3', title: 'Summit Day', desc: 'Climb to Sandakphu and watch the sunrise panorama.' },
      { day: 'Day 4', title: 'Descent', desc: 'Forest descent and overnight stay.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to base and transfer to Siliguri.' },
    ],
    inclusions: ['Stay on trek', 'Meals on trek', 'Guide', 'Porter', 'Permits', 'First aid'],
    exclusions: ['Transport to Siliguri', 'Gear rental', 'Insurance'],
    isFeatured: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'lachung-yumthang',
    slug: 'lachung-yumthang-valley',
    title: 'Lachung and Yumthang Valley',
    destination: 'North Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 4,
    days: 5,
    minPax: 4,
    badge: 'Seasonal',
    badgeColor: 'teal',
    imageUrl: getPackageCover('lachung-yumthang') || 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    gallery: getPackageGallery('lachung-yumthang'),
    description:
      'A scenic North Sikkim journey through alpine valleys, rivers, seasonal flowers, and mountain villages.',
    highlights: ['Yumthang Valley', 'Zero Point', 'Lachung Village', 'Rhododendrons', 'Glacial streams'],
    tags: ['Valley', 'Flowers', 'North Sikkim'],
    location: { lat: 27.8167, lng: 88.7167, mapUrl: 'https://maps.google.com/?q=Yumthang+Valley,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Gangtok to Lachung', desc: 'Drive through river valleys and mountain roads.' },
      { day: 'Day 2', title: 'Yumthang and Zero Point', desc: 'Visit the valley and optional Zero Point excursion.' },
      { day: 'Day 3', title: 'Village Exploration', desc: 'Discover local culture and monastery life.' },
      { day: 'Day 4', title: 'Return to Gangtok', desc: 'Scenic drive back.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer toward NJP or Siliguri.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast and dinner', 'Permits', 'Transfers', 'Guide'],
    exclusions: ['Optional excursions', 'Lunch', 'Personal expenses', 'Insurance'],
    isFeatured: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'leh-ladakh-highlights',
    slug: 'leh-ladakh-highlights',
    title: 'Leh Ladakh Highlights',
    destination: 'Leh, Nubra, Pangong - Ladakh',
    states: ['Ladakh'],
    category: 'ladakh',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Top Pick',
    badgeColor: 'amber',
    imageUrl: getPackageCover('leh-ladakh-highlights') || ladakhThikseyMonastery,
    gallery: [...getPackageGallery('leh-ladakh-highlights'),
      ladakhNubraCamelSafari,
      ladakhPangongLake,
      ladakhHikkimVillage,
      ladakhNubraValleyRiver,
    ],
    description:
      'A classic Ladakh circuit covering high passes, monasteries, Nubra dunes, and the stunning blue waters of Pangong.',
    highlights: ['Khardung La', 'Nubra Valley', 'Pangong Lake', 'Shanti Stupa', 'Monasteries'],
    tags: ['Mountains', 'Adventure', 'Road Trip'],
    location: { lat: 34.1526, lng: 77.577, mapUrl: 'https://maps.google.com/?q=Leh,Ladakh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Leh', desc: 'Hotel check-in and easy acclimatization day.' },
      { day: 'Day 2', title: 'Leh Local Sightseeing', desc: 'Shanti Stupa, Palace area, and market stroll.' },
      { day: 'Day 3', title: 'Nubra Valley', desc: 'Drive via Khardung La and enjoy the valley landscapes.' },
      { day: 'Day 4', title: 'Pangong Lake', desc: 'High-altitude drive to the iconic lake.' },
      { day: 'Day 5', title: 'Monasteries Route', desc: 'Scenic monasteries and river confluence viewpoints.' },
      { day: 'Day 6', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing', 'Permits'],
    exclusions: ['Flights', 'Lunch and dinner', 'Personal expenses', 'Optional activities'],
    isFeatured: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'kashmir-gulmarg-pahalgam',
    slug: 'kashmir-gulmarg-pahalgam',
    title: 'Kashmir Valley Escape',
    destination: 'Srinagar, Gulmarg, Pahalgam - Jammu & Kashmir',
    states: ['Jammu & Kashmir'],
    category: 'kashmir',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Popular',
    badgeColor: 'blue',
    imageUrl: getPackageCover('kashmir-gulmarg-pahalgam') || 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    gallery: [...getPackageGallery('kashmir-gulmarg-pahalgam'), 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'Dal Lake serenity, Mughal gardens, and scenic day trips to Gulmarg and Pahalgam for a relaxed mountain holiday.',
    highlights: ['Dal Lake Shikara', 'Gulmarg Meadows', 'Pahalgam Valley', 'Mughal Gardens'],
    tags: ['Nature', 'Valleys', 'Relax'],
    location: { lat: 34.0837, lng: 74.7973, mapUrl: 'https://maps.google.com/?q=Srinagar,Jammu+and+Kashmir' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Srinagar', desc: 'Check-in and evening Dal Lake experience.' },
      { day: 'Day 2', title: 'Srinagar Gardens', desc: 'Mughal gardens and local markets.' },
      { day: 'Day 3', title: 'Gulmarg Day Trip', desc: 'Meadows and optional gondola ride.' },
      { day: 'Day 4', title: 'Pahalgam Day Trip', desc: 'Valley views and river-side time.' },
      { day: 'Day 5', title: 'Leisure Day', desc: 'Flexible day for shopping and experiences.' },
      { day: 'Day 6', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional rides'],
    isFeatured: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'himachal-manali-kasol',
    slug: 'himachal-manali-kasol',
    title: 'Manali and Kasol Getaway',
    destination: 'Manali, Solang, Kasol - Himachal Pradesh',
    states: ['Himachal Pradesh'],
    category: 'himachal',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Best Seller',
    badgeColor: 'red',
    imageUrl: getPackageCover('himachal-manali-kasol') || 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    gallery: [...getPackageGallery('himachal-manali-kasol'), 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'A crowd-favorite Himachal route with mountain views, cafes, and adventure options around Solang and nearby valleys.',
    highlights: ['Solang Valley', 'Old Manali', 'Parvati Valley', 'Cafe Hopping'],
    tags: ['Mountains', 'Leisure', 'Adventure'],
    location: { lat: 32.2396, lng: 77.1887, mapUrl: 'https://maps.google.com/?q=Manali,Himachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Manali', desc: 'Hotel check-in and local walk.' },
      { day: 'Day 2', title: 'Solang and Views', desc: 'Solang Valley activities and viewpoints.' },
      { day: 'Day 3', title: 'Kasol Transfer', desc: 'Drive to Kasol, riverside evening.' },
      { day: 'Day 4', title: 'Parvati Valley', desc: 'Explore nearby spots and cafes.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing'],
    exclusions: ['Transport to Himachal', 'Adventure activities', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 'uttarakhand-rishikesh-mussoorie',
    slug: 'uttarakhand-rishikesh-mussoorie',
    title: 'Rishikesh and Mussoorie Retreat',
    destination: 'Rishikesh, Mussoorie - Uttarakhand',
    states: ['Uttarakhand'],
    category: 'uttarakhand',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Relax',
    badgeColor: 'teal',
    imageUrl: getPackageCover('uttarakhand-rishikesh-mussoorie') || 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    gallery: [...getPackageGallery('uttarakhand-rishikesh-mussoorie'), 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'A balanced Uttarakhand trip combining the calm of Rishikesh with the viewpoints and mall-road charm of Mussoorie.',
    highlights: ['Ganga Aarti', 'River Views', 'Mussoorie Viewpoints', 'Local Markets'],
    tags: ['Relax', 'Nature', 'Spiritual'],
    location: { lat: 30.0869, lng: 78.2676, mapUrl: 'https://maps.google.com/?q=Rishikesh,Uttarakhand' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Rishikesh', desc: 'Check-in and evening aarti.' },
      { day: 'Day 2', title: 'Rishikesh Sightseeing', desc: 'Ghats and viewpoints at your pace.' },
      { day: 'Day 3', title: 'Mussoorie', desc: 'Drive to Mussoorie and explore the town.' },
      { day: 'Day 4', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Transport to Uttarakhand', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 'arunachal-tawang-monasteries',
    slug: 'arunachal-tawang-monasteries',
    title: 'Tawang Monasteries and Lakes',
    destination: 'Tawang - Arunachal Pradesh',
    states: ['Arunachal Pradesh'],
    category: 'arunachal',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Offbeat',
    badgeColor: 'purple',
    imageUrl: getPackageCover('arunachal-tawang-monasteries') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: [...getPackageGallery('arunachal-tawang-monasteries'), 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80'],
    description:
      'A scenic Arunachal journey focused on Tawang’s monasteries, mountain passes, and high-altitude lakes.',
    highlights: ['Tawang Monastery', 'Sela Pass', 'High-Altitude Lakes', 'Local Culture'],
    tags: ['Offbeat', 'Mountains', 'Culture'],
    location: { lat: 27.5864, lng: 91.8597, mapUrl: 'https://maps.google.com/?q=Tawang,Arunachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival and Transfer', desc: 'Begin the mountain route and settle in.' },
      { day: 'Day 2', title: 'Pass and Views', desc: 'Sela Pass and lake stops.' },
      { day: 'Day 3', title: 'Monastery Day', desc: 'Explore the monastery and viewpoints.' },
      { day: 'Day 4', title: 'Local Experiences', desc: 'Markets and cultural stops.' },
      { day: 'Day 5', title: 'Leisure / Buffer', desc: 'Flexible day for weather and permits.' },
      { day: 'Day 6', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Permits assistance'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 'assam-kaziranga-wildlife',
    slug: 'assam-kaziranga-wildlife',
    title: 'Kaziranga Wildlife Safari',
    destination: 'Kaziranga - Assam',
    states: ['Assam'],
    category: 'assam',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Wildlife',
    badgeColor: 'green',
    imageUrl: getPackageCover('assam-kaziranga-wildlife') || 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    gallery: [...getPackageGallery('assam-kaziranga-wildlife'), 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80'],
    description:
      'A short and powerful wildlife break in Kaziranga, home to the one-horned rhinoceros and rich birdlife.',
    highlights: ['Jeep Safari', 'Rhino Spotting', 'Birding', 'Nature Trails'],
    tags: ['Wildlife', 'Nature', 'Safari'],
    location: { lat: 26.5775, lng: 93.1711, mapUrl: 'https://maps.google.com/?q=Kaziranga,Assam' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Resort check-in and evening nature walk.' },
      { day: 'Day 2', title: 'Safari Day', desc: 'Jeep safari and local experiences.' },
      { day: 'Day 3', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Safari assistance'],
    exclusions: ['Transport to Assam', 'Safari tickets', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 'meghalaya-shillong-cherrapunji',
    slug: 'meghalaya-shillong-cherrapunji',
    title: 'Meghalaya Waterfalls and Caves',
    destination: 'Shillong, Cherrapunji, Dawki - Meghalaya',
    states: ['Meghalaya'],
    category: 'meghalaya',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Trending',
    badgeColor: 'orange',
    imageUrl: getPackageCover('meghalaya-shillong-cherrapunji') || 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
    gallery: [...getPackageGallery('meghalaya-shillong-cherrapunji'), 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'],
    description:
      'Blue rivers, misty waterfalls, limestone caves, and viewpoints across Meghalaya’s most loved circuit.',
    highlights: ['Dawki River', 'Cherrapunji Falls', 'Caves', 'Viewpoints'],
    tags: ['Nature', 'Waterfalls', 'Road Trip'],
    location: { lat: 25.5788, lng: 91.8933, mapUrl: 'https://maps.google.com/?q=Shillong,Meghalaya' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Shillong', desc: 'Check-in and local evening.' },
      { day: 'Day 2', title: 'Cherrapunji', desc: 'Waterfalls and viewpoints.' },
      { day: 'Day 3', title: 'Caves and Trails', desc: 'Cave visit and scenic drives.' },
      { day: 'Day 4', title: 'Dawki Day', desc: 'Crystal-clear river experience.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Transport to Meghalaya', 'Entry fees', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 'kerala-backwaters-munnar',
    slug: 'kerala-backwaters-munnar',
    title: 'Kerala Backwaters and Tea Hills',
    destination: 'Munnar, Alleppey, Kochi - Kerala',
    states: ['Kerala'],
    category: 'kerala',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Family',
    badgeColor: 'blue',
    imageUrl: getPackageCover('kerala-backwaters-munnar') || 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800&q=80',
    gallery: [...getPackageGallery('kerala-backwaters-munnar'), 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'],
    description:
      'A classic Kerala mix of hill-station tea gardens, backwater calm, and city highlights for a smooth vacation.',
    highlights: ['Munnar Tea Gardens', 'Backwaters', 'Houseboat Experience', 'Kochi'],
    tags: ['Relax', 'Nature', 'Family'],
    location: { lat: 9.9312, lng: 76.2673, mapUrl: 'https://maps.google.com/?q=Kochi,Kerala' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Kochi', desc: 'Check-in and local sightseeing.' },
      { day: 'Day 2', title: 'Munnar', desc: 'Drive to Munnar and explore tea hills.' },
      { day: 'Day 3', title: 'Munnar Sightseeing', desc: 'Viewpoints and gardens.' },
      { day: 'Day 4', title: 'Backwaters', desc: 'Transfer to Alleppey for backwaters.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to Kochi and depart.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional experiences'],
    isFeatured: true,
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 'nepal-kathmandu',
    slug: 'nepal-kathmandu',
    title: 'Kathmandu Heritage Explorer',
    destination: 'Kathmandu - Nepal',
    states: ['Kathmandu'],
    category: 'nepal',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'International',
    badgeColor: 'teal',
    imageUrl: getPackageCover('nepal-kathmandu') || 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80',
    gallery: [...getPackageGallery('nepal-kathmandu'), 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'],
    description:
      'Temples, heritage squares, and Himalayan culture in the heart of Kathmandu valley.',
    highlights: ['Kathmandu Temples', 'Durbar Square', 'Local Markets', 'Pashupatinath'],
    tags: ['Culture', 'International'],
    location: { lat: 27.7172, lng: 85.324, mapUrl: 'https://maps.google.com/?q=Kathmandu,Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Kathmandu', desc: 'Check-in and local evening.' },
      { day: 'Day 2', title: 'Heritage Tour', desc: 'Temples and heritage squares.' },
      { day: 'Day 3', title: 'Pashupatinath and Markets', desc: 'Temple visit and local market exploration.' },
      { day: 'Day 4', title: 'Departure', desc: 'Departure transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['International flights', 'Visa fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 'nepal-pokhara',
    slug: 'nepal-pokhara',
    title: 'Pokhara Lakeside Retreat',
    destination: 'Pokhara - Nepal',
    states: ['Pokhara'],
    category: 'nepal',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'International',
    badgeColor: 'teal',
    imageUrl: getPackageCover('nepal-pokhara') || 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
    gallery: [...getPackageGallery('nepal-pokhara'), 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80'],
    description:
      'Lakeside calm and Himalayan sunrise views in Nepal’s most scenic valley town.',
    highlights: ['Pokhara Lakeside', 'Sunrise Viewpoint', 'Phewa Lake', 'Local Markets'],
    tags: ['Views', 'International', 'Peaceful'],
    location: { lat: 28.2096, lng: 83.9856, mapUrl: 'https://maps.google.com/?q=Pokhara,Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Pokhara', desc: 'Check-in and relax lakeside.' },
      { day: 'Day 2', title: 'Sunrise Viewpoint', desc: 'Early sunrise viewpoint and sightseeing.' },
      { day: 'Day 3', title: 'Phewa Lake and Markets', desc: 'Boating on Phewa Lake and local markets.' },
      { day: 'Day 4', title: 'Departure', desc: 'Departure transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['International flights', 'Visa fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 21,
  },
  {
    id: 'nepal-upper-mustang',
    slug: 'nepal-upper-mustang',
    title: 'Upper Mustang Heritage Trail',
    destination: 'Mustang - Nepal',
    states: ['Mustang'],
    category: 'nepal',
    nights: 6,
    days: 7,
    minPax: 2,
    badge: 'International',
    badgeColor: 'teal',
    imageUrl: getPackageCover('nepal-upper-mustang') || 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    gallery: [...getPackageGallery('nepal-upper-mustang'), 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80'],
    description:
      'A high-altitude desert journey through Mustang’s walled city of Lo Manthang, ancient monasteries, and dramatic Himalayan rain-shadow landscapes.',
    highlights: ['Lo Manthang Walled City', 'Ancient Monasteries', 'Kagbeni Village', 'High Desert Landscapes'],
    tags: ['Culture', 'Trekking', 'International', 'Offbeat'],
    location: { lat: 29.1872, lng: 83.9620, mapUrl: 'https://maps.google.com/?q=Mustang,Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Pokhara', desc: 'Check-in and preparation for the Mustang drive.' },
      { day: 'Day 2', title: 'Drive to Jomsom', desc: 'Scenic drive through the Kali Gandaki gorge.' },
      { day: 'Day 3', title: 'Kagbeni to Chele', desc: 'Enter Upper Mustang and cross into the restricted area.' },
      { day: 'Day 4', title: 'Onward to Lo Manthang', desc: 'Continue through desert valleys to the walled city.' },
      { day: 'Day 5', title: 'Lo Manthang Exploration', desc: 'Monasteries, palace, and local culture.' },
      { day: 'Day 6', title: 'Return Journey', desc: 'Drive back towards Jomsom and Pokhara.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer out and depart.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Restricted area permit assistance'],
    exclusions: ['International flights', 'Visa fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    id: 'bhutan-paro',
    slug: 'bhutan-paro',
    title: 'Paro Valley Escape',
    destination: 'Paro - Bhutan',
    states: ['Paro'],
    category: 'bhutan',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'International',
    badgeColor: 'purple',
    imageUrl: getPackageCover('bhutan-paro') || 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
    gallery: [...getPackageGallery('bhutan-paro'), 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'],
    description:
      'A gentle introduction to Bhutan’s Paro valley, with cultural sights and scenic mountain drives.',
    highlights: ['Paro Valley', 'Tiger’s Nest Monastery', 'Scenic Drives', 'Local Markets'],
    tags: ['Culture', 'International', 'Peaceful'],
    location: { lat: 27.4305, lng: 89.4133, mapUrl: 'https://maps.google.com/?q=Paro,Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Paro', desc: 'Check-in and local sightseeing.' },
      { day: 'Day 2', title: 'Tiger’s Nest Hike', desc: 'Hike to the iconic Tiger’s Nest Monastery.' },
      { day: 'Day 3', title: 'Culture Day', desc: 'Monasteries, markets, and viewpoints.' },
      { day: 'Day 4', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Visa/permit fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    id: 'bhutan-thimphu',
    slug: 'bhutan-thimphu',
    title: 'Thimphu City Discovery',
    destination: 'Thimphu - Bhutan',
    states: ['Thimphu'],
    category: 'bhutan',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'International',
    badgeColor: 'purple',
    imageUrl: getPackageCover('bhutan-thimphu') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: [...getPackageGallery('bhutan-thimphu'), 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'Explore Bhutan’s calm capital city, its monasteries, markets, and mountain viewpoints.',
    highlights: ['Thimphu Culture', 'Buddha Dordenma', 'Local Markets', 'Mountain Viewpoints'],
    tags: ['Culture', 'International', 'Peaceful'],
    location: { lat: 27.4728, lng: 89.639, mapUrl: 'https://maps.google.com/?q=Thimphu,Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Thimphu', desc: 'Check-in and local evening.' },
      { day: 'Day 2', title: 'City Tour', desc: 'Buddha Dordenma and city monasteries.' },
      { day: 'Day 3', title: 'Markets and Viewpoints', desc: 'Local markets and mountain viewpoints.' },
      { day: 'Day 4', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Visa/permit fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 'bhutan-punakha',
    slug: 'bhutan-punakha',
    title: 'Punakha Valley Discovery',
    destination: 'Punakha - Bhutan',
    states: ['Punakha'],
    category: 'bhutan',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'International',
    badgeColor: 'purple',
    imageUrl: getPackageCover('bhutan-punakha') || 'https://images.unsplash.com/photo-1553376656-2dd5c8d6d4b3?w=800&q=80',
    gallery: [...getPackageGallery('bhutan-punakha'), 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80'],
    description:
      'Cross the scenic Dochula Pass into Punakha valley, home to Bhutan’s most beautiful fortress and gentle riverside walks.',
    highlights: ['Punakha Dzong', 'Dochula Pass', 'Suspension Bridge', 'Riverside Walks'],
    tags: ['Culture', 'International', 'Scenic'],
    location: { lat: 27.5916, lng: 89.8775, mapUrl: 'https://maps.google.com/?q=Punakha,Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Paro', desc: 'Check-in and local sightseeing.' },
      { day: 'Day 2', title: 'Dochula Pass to Punakha', desc: 'Scenic drive over Dochula Pass into Punakha valley.' },
      { day: 'Day 3', title: 'Punakha Dzong', desc: 'Visit the fortress and the longest suspension bridge.' },
      { day: 'Day 4', title: 'Riverside Day', desc: 'Leisure walks and local village visits.' },
      { day: 'Day 5', title: 'Return to Paro', desc: 'Drive back over Dochula Pass.' },
      { day: 'Day 6', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Visa/permit fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'pangong-lake',
    slug: 'pangong-lake-highlight',
    title: 'Pangong Lake Discovery',
    destination: 'Pangong Lake - Ladakh',
    states: ['Ladakh'],
    category: 'ladakh',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('pangong-lake') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('pangong-lake'),
    description:
      'A high-altitude lake famous for its ever-changing shades of blue, ringed by stark mountains.',
    highlights: ['Pangong Lake', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Lakes", "Mountains", "Photography"],
    location: { lat: 33.7592, lng: 78.6641, mapUrl: 'https://maps.google.com/?q=Ladakh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Pangong Lake and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Pangong Lake Visit', desc: 'Full day exploring Pangong Lake with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 23,
  },
  {
    id: 'magnetic-hill',
    slug: 'magnetic-hill-highlight',
    title: 'Magnetic Hill Discovery',
    destination: 'Magnetic Hill - Ladakh',
    states: ['Ladakh'],
    category: 'ladakh',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('magnetic-hill') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('magnetic-hill'),
    description:
      'A curious stretch of road with an optical illusion where vehicles appear to roll uphill on their own.',
    highlights: ['Magnetic Hill', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Offbeat", "Road Trip", "Curiosity"],
    location: { lat: 34.2431, lng: 77.4181, mapUrl: 'https://maps.google.com/?q=Ladakh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Magnetic Hill and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Magnetic Hill Visit', desc: 'Full day exploring Magnetic Hill with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 24,
  },
  {
    id: 'thiksey-monastery',
    slug: 'thiksey-monastery-highlight',
    title: 'Thiksey Monastery Discovery',
    destination: 'Thiksey Monastery - Ladakh',
    states: ['Ladakh'],
    category: 'ladakh',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('thiksey-monastery') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('thiksey-monastery'),
    description:
      'A striking cliffside monastery often compared to a mini Potala Palace, with sweeping valley views.',
    highlights: ['Thiksey Monastery', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Monastery", "Culture", "Views"],
    location: { lat: 33.8813, lng: 77.6636, mapUrl: 'https://maps.google.com/?q=Ladakh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Thiksey Monastery and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Thiksey Monastery Visit', desc: 'Full day exploring Thiksey Monastery with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 25,
  },
  {
    id: 'dal-lake',
    slug: 'dal-lake-highlight',
    title: 'Dal Lake Discovery',
    destination: 'Dal Lake - Srinagar, Jammu & Kashmir',
    states: ['Jammu & Kashmir'],
    category: 'kashmir',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('dal-lake') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('dal-lake'),
    description:
      'Iconic shikara rides and houseboats on Srinagar’s most famous lake.',
    highlights: ['Dal Lake', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Lakes", "Houseboat", "Relax"],
    location: { lat: 34.1237, lng: 74.8237, mapUrl: 'https://maps.google.com/?q=Srinagar+Jammu+&+Kashmir' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Dal Lake and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Dal Lake Visit', desc: 'Full day exploring Dal Lake with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 26,
  },
  {
    id: 'gulmarg-gondola',
    slug: 'gulmarg-gondola-highlight',
    title: 'Gulmarg Gondola Discovery',
    destination: 'Gulmarg Gondola - Gulmarg, Jammu & Kashmir',
    states: ['Jammu & Kashmir'],
    category: 'kashmir',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('gulmarg-gondola') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('gulmarg-gondola'),
    description:
      'One of the world’s highest cable cars, lifting you over meadows and snow-capped peaks.',
    highlights: ['Gulmarg Gondola', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Cable Car", "Snow", "Views"],
    location: { lat: 34.0484, lng: 74.3805, mapUrl: 'https://maps.google.com/?q=Gulmarg+Jammu+&+Kashmir' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Gulmarg Gondola and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Gulmarg Gondola Visit', desc: 'Full day exploring Gulmarg Gondola with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 27,
  },
  {
    id: 'mughal-gardens',
    slug: 'mughal-gardens-highlight',
    title: 'Mughal Gardens Discovery',
    destination: 'Mughal Gardens - Srinagar, Jammu & Kashmir',
    states: ['Jammu & Kashmir'],
    category: 'kashmir',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('mughal-gardens') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('mughal-gardens'),
    description:
      'Terraced Mughal-era gardens with fountains and flowerbeds overlooking Dal Lake.',
    highlights: ['Mughal Gardens', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Gardens", "Heritage", "Culture"],
    location: { lat: 34.1256, lng: 74.8798, mapUrl: 'https://maps.google.com/?q=Srinagar+Jammu+&+Kashmir' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Mughal Gardens and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Mughal Gardens Visit', desc: 'Full day exploring Mughal Gardens with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 28,
  },
  {
    id: 'solang-valley',
    slug: 'solang-valley-highlight',
    title: 'Solang Valley Discovery',
    destination: 'Solang Valley - Manali, Himachal Pradesh',
    states: ['Himachal Pradesh'],
    category: 'himachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('solang-valley') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('solang-valley'),
    description:
      'Adventure sports and snow-capped views just outside Manali.',
    highlights: ['Solang Valley', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Adventure", "Snow", "Views"],
    location: { lat: 32.317, lng: 77.157, mapUrl: 'https://maps.google.com/?q=Manali+Himachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Solang Valley and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Solang Valley Visit', desc: 'Full day exploring Solang Valley with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 29,
  },
  {
    id: 'old-manali',
    slug: 'old-manali-highlight',
    title: 'Old Manali Discovery',
    destination: 'Old Manali - Manali, Himachal Pradesh',
    states: ['Himachal Pradesh'],
    category: 'himachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('old-manali') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('old-manali'),
    description:
      'Cafes, riverside lanes, and a laid-back mountain-town vibe.',
    highlights: ['Old Manali', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Cafes", "Leisure", "Riverside"],
    location: { lat: 32.2532, lng: 77.1641, mapUrl: 'https://maps.google.com/?q=Manali+Himachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Old Manali and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Old Manali Visit', desc: 'Full day exploring Old Manali with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 30,
  },
  {
    id: 'rohtang-pass',
    slug: 'rohtang-pass-highlight',
    title: 'Rohtang Pass Discovery',
    destination: 'Rohtang Pass - Manali, Himachal Pradesh',
    states: ['Himachal Pradesh'],
    category: 'himachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('rohtang-pass') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('rohtang-pass'),
    description:
      'A dramatic high-altitude pass with glaciers and panoramic Himalayan views.',
    highlights: ['Rohtang Pass', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["High Pass", "Snow", "Adventure"],
    location: { lat: 32.3728, lng: 77.2495, mapUrl: 'https://maps.google.com/?q=Manali+Himachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Rohtang Pass and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Rohtang Pass Visit', desc: 'Full day exploring Rohtang Pass with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 31,
  },
  {
    id: 'ganga-aarti-rishikesh',
    slug: 'ganga-aarti-rishikesh-highlight',
    title: 'Ganga Aarti, Rishikesh Discovery',
    destination: 'Ganga Aarti, Rishikesh - Rishikesh, Uttarakhand',
    states: ['Uttarakhand'],
    category: 'uttarakhand',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('ganga-aarti-rishikesh') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('ganga-aarti-rishikesh'),
    description:
      'A mesmerizing riverside prayer ceremony on the banks of the Ganga at sunset.',
    highlights: ['Ganga Aarti, Rishikesh', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Spiritual", "Riverside", "Culture"],
    location: { lat: 30.122, lng: 78.308, mapUrl: 'https://maps.google.com/?q=Rishikesh+Uttarakhand' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Ganga Aarti, Rishikesh and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Ganga Aarti, Rishikesh Visit', desc: 'Full day exploring Ganga Aarti, Rishikesh with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 32,
  },
  {
    id: 'mussoorie-mall-road',
    slug: 'mussoorie-mall-road-highlight',
    title: 'Mussoorie Mall Road Discovery',
    destination: 'Mussoorie Mall Road - Mussoorie, Uttarakhand',
    states: ['Uttarakhand'],
    category: 'uttarakhand',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('mussoorie-mall-road') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('mussoorie-mall-road'),
    description:
      'A charming hill-station promenade with viewpoints, cafes, and old-world charm.',
    highlights: ['Mussoorie Mall Road', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Hill Station", "Leisure", "Views"],
    location: { lat: 30.4598, lng: 78.0664, mapUrl: 'https://maps.google.com/?q=Mussoorie+Uttarakhand' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Mussoorie Mall Road and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Mussoorie Mall Road Visit', desc: 'Full day exploring Mussoorie Mall Road with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 'valley-of-flowers',
    slug: 'valley-of-flowers-highlight',
    title: 'Valley of Flowers Discovery',
    destination: 'Valley of Flowers - Chamoli, Uttarakhand',
    states: ['Uttarakhand'],
    category: 'uttarakhand',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('valley-of-flowers') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('valley-of-flowers'),
    description:
      'A UNESCO-listed alpine meadow bursting with seasonal Himalayan blooms.',
    highlights: ['Valley of Flowers', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Trek", "Nature", "UNESCO"],
    location: { lat: 30.7268, lng: 79.6045, mapUrl: 'https://maps.google.com/?q=Chamoli+Uttarakhand' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Valley of Flowers and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Valley of Flowers Visit', desc: 'Full day exploring Valley of Flowers with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 34,
  },
  {
    id: 'tiger-hill',
    slug: 'tiger-hill-highlight',
    title: 'Tiger Hill Discovery',
    destination: 'Tiger Hill - Darjeeling, West Bengal',
    states: ['Darjeeling'],
    category: 'darjeeling',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('tiger-hill') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('tiger-hill'),
    description:
      'The classic sunrise viewpoint over Kanchenjunga, the world’s third-highest peak.',
    highlights: ['Tiger Hill', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Sunrise", "Views", "Himalaya"],
    location: { lat: 27.0, lng: 88.2635, mapUrl: 'https://maps.google.com/?q=Darjeeling+West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Tiger Hill and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Tiger Hill Visit', desc: 'Full day exploring Tiger Hill with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 35,
  },
  {
    id: 'darjeeling-toy-train',
    slug: 'darjeeling-toy-train-highlight',
    title: 'Darjeeling Toy Train Discovery',
    destination: 'Darjeeling Toy Train - Darjeeling, West Bengal',
    states: ['Darjeeling'],
    category: 'darjeeling',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('darjeeling-toy-train') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('darjeeling-toy-train'),
    description:
      'A joyride on the UNESCO-listed narrow-gauge railway winding through the hills.',
    highlights: ['Darjeeling Toy Train', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Heritage", "UNESCO", "Railway"],
    location: { lat: 27.041, lng: 88.2663, mapUrl: 'https://maps.google.com/?q=Darjeeling+West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Darjeeling Toy Train and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Darjeeling Toy Train Visit', desc: 'Full day exploring Darjeeling Toy Train with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 36,
  },
  {
    id: 'tea-gardens',
    slug: 'tea-gardens-highlight',
    title: 'Tea Gardens Discovery',
    destination: 'Tea Gardens - Darjeeling, West Bengal',
    states: ['Darjeeling'],
    category: 'darjeeling',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('tea-gardens') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('tea-gardens'),
    description:
      'Rolling estates producing some of the world’s finest tea, with guided walks and tastings.',
    highlights: ['Tea Gardens', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Tea", "Nature", "Culture"],
    location: { lat: 27.049, lng: 88.247, mapUrl: 'https://maps.google.com/?q=Darjeeling+West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Tea Gardens and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Tea Gardens Visit', desc: 'Full day exploring Tea Gardens with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 37,
  },
  {
    id: 'tsomgo-lake',
    slug: 'tsomgo-lake-highlight',
    title: 'Tsomgo Lake Discovery',
    destination: 'Tsomgo Lake - East Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('tsomgo-lake') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('tsomgo-lake'),
    description:
      'A glacial lake at high altitude, often rimmed with snow and surrounded by prayer flags.',
    highlights: ['Tsomgo Lake', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Lakes", "High Altitude", "Views"],
    location: { lat: 27.3747, lng: 88.7614, mapUrl: 'https://maps.google.com/?q=East+Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Tsomgo Lake and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Tsomgo Lake Visit', desc: 'Full day exploring Tsomgo Lake with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 38,
  },
  {
    id: 'rumtek-monastery',
    slug: 'rumtek-monastery-highlight',
    title: 'Rumtek Monastery Discovery',
    destination: 'Rumtek Monastery - Gangtok, Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('rumtek-monastery') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('rumtek-monastery'),
    description:
      'One of Sikkim’s largest and most significant Buddhist monasteries.',
    highlights: ['Rumtek Monastery', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Monastery", "Culture", "Spiritual"],
    location: { lat: 27.2865, lng: 88.5619, mapUrl: 'https://maps.google.com/?q=Gangtok+Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Rumtek Monastery and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Rumtek Monastery Visit', desc: 'Full day exploring Rumtek Monastery with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 39,
  },
  {
    id: 'nathula-pass',
    slug: 'nathula-pass-highlight',
    title: 'Nathula Pass Discovery',
    destination: 'Nathula Pass - East Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('nathula-pass') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('nathula-pass'),
    description:
      'A historic Indo-China border pass on the old Silk Route, with dramatic mountain scenery.',
    highlights: ['Nathula Pass', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Border Pass", "History", "Adventure"],
    location: { lat: 27.386, lng: 88.8419, mapUrl: 'https://maps.google.com/?q=East+Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Nathula Pass and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Nathula Pass Visit', desc: 'Full day exploring Nathula Pass with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 40,
  },
  {
    id: 'tawang-monastery',
    slug: 'tawang-monastery-highlight',
    title: 'Tawang Monastery Discovery',
    destination: 'Tawang Monastery - Tawang, Arunachal Pradesh',
    states: ['Arunachal Pradesh'],
    category: 'arunachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('tawang-monastery') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('tawang-monastery'),
    description:
      'India’s largest monastery, perched high above the Tawang valley.',
    highlights: ['Tawang Monastery', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Monastery", "Culture", "Offbeat"],
    location: { lat: 27.5859, lng: 91.8593, mapUrl: 'https://maps.google.com/?q=Tawang+Arunachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Tawang Monastery and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Tawang Monastery Visit', desc: 'Full day exploring Tawang Monastery with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 41,
  },
  {
    id: 'sela-pass',
    slug: 'sela-pass-highlight',
    title: 'Sela Pass Discovery',
    destination: 'Sela Pass - Tawang, Arunachal Pradesh',
    states: ['Arunachal Pradesh'],
    category: 'arunachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('sela-pass') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('sela-pass'),
    description:
      'A scenic high-altitude pass with a sacred lake and prayer-flag-lined viewpoints.',
    highlights: ['Sela Pass', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["High Pass", "Lakes", "Adventure"],
    location: { lat: 27.7167, lng: 92.1, mapUrl: 'https://maps.google.com/?q=Tawang+Arunachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Sela Pass and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Sela Pass Visit', desc: 'Full day exploring Sela Pass with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 42,
  },
  {
    id: 'ziro-valley',
    slug: 'ziro-valley-highlight',
    title: 'Ziro Valley Discovery',
    destination: 'Ziro Valley - Ziro, Arunachal Pradesh',
    states: ['Arunachal Pradesh'],
    category: 'arunachal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('ziro-valley') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('ziro-valley'),
    description:
      'A tranquil valley of rice fields and pine hills, home to the Apatani community.',
    highlights: ['Ziro Valley', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Valley", "Culture", "Offbeat"],
    location: { lat: 27.6, lng: 93.83, mapUrl: 'https://maps.google.com/?q=Ziro+Arunachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Ziro Valley and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Ziro Valley Visit', desc: 'Full day exploring Ziro Valley with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 43,
  },
  {
    id: 'kaziranga-national-park',
    slug: 'kaziranga-national-park-highlight',
    title: 'Kaziranga National Park Discovery',
    destination: 'Kaziranga National Park - Kaziranga, Assam',
    states: ['Assam'],
    category: 'assam',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('kaziranga-national-park') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('kaziranga-national-park'),
    description:
      'Home to the one-horned rhinoceros and some of India’s richest birdlife.',
    highlights: ['Kaziranga National Park', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Wildlife", "Safari", "Nature"],
    location: { lat: 26.5775, lng: 93.1711, mapUrl: 'https://maps.google.com/?q=Kaziranga+Assam' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Kaziranga National Park and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Kaziranga National Park Visit', desc: 'Full day exploring Kaziranga National Park with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 44,
  },
  {
    id: 'kamakhya-temple',
    slug: 'kamakhya-temple-highlight',
    title: 'Kamakhya Temple Discovery',
    destination: 'Kamakhya Temple - Guwahati, Assam',
    states: ['Assam'],
    category: 'assam',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('kamakhya-temple') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('kamakhya-temple'),
    description:
      'A revered Shakti temple perched on Nilachal Hill overlooking Guwahati.',
    highlights: ['Kamakhya Temple', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Spiritual", "Heritage", "Views"],
    location: { lat: 26.1665, lng: 91.7036, mapUrl: 'https://maps.google.com/?q=Guwahati+Assam' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Kamakhya Temple and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Kamakhya Temple Visit', desc: 'Full day exploring Kamakhya Temple with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 45,
  },
  {
    id: 'majuli-island',
    slug: 'majuli-island-highlight',
    title: 'Majuli Island Discovery',
    destination: 'Majuli Island - Majuli, Assam',
    states: ['Assam'],
    category: 'assam',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('majuli-island') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('majuli-island'),
    description:
      'The world’s largest river island, dotted with satras (monasteries) and mask-making villages.',
    highlights: ['Majuli Island', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Island", "Culture", "Offbeat"],
    location: { lat: 26.95, lng: 94.17, mapUrl: 'https://maps.google.com/?q=Majuli+Assam' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Majuli Island and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Majuli Island Visit', desc: 'Full day exploring Majuli Island with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 46,
  },
  {
    id: 'living-root-bridges',
    slug: 'living-root-bridges-highlight',
    title: 'Living Root Bridges Discovery',
    destination: 'Living Root Bridges - Nongriat, Meghalaya',
    states: ['Meghalaya'],
    category: 'meghalaya',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('living-root-bridges') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('living-root-bridges'),
    description:
      'Extraordinary bridges grown from living tree roots over generations, reached by a scenic trek.',
    highlights: ['Living Root Bridges', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Trek", "Nature", "Unique"],
    location: { lat: 25.245, lng: 91.669, mapUrl: 'https://maps.google.com/?q=Nongriat+Meghalaya' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Living Root Bridges and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Living Root Bridges Visit', desc: 'Full day exploring Living Root Bridges with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 47,
  },
  {
    id: 'cherrapunji-waterfalls',
    slug: 'cherrapunji-waterfalls-highlight',
    title: 'Cherrapunji Waterfalls Discovery',
    destination: 'Cherrapunji Waterfalls - Cherrapunji, Meghalaya',
    states: ['Meghalaya'],
    category: 'meghalaya',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('cherrapunji-waterfalls') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('cherrapunji-waterfalls'),
    description:
      'Dramatic falls, including the famous Nohkalikai, in one of the wettest places on Earth.',
    highlights: ['Cherrapunji Waterfalls', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Waterfalls", "Nature", "Views"],
    location: { lat: 25.2919, lng: 91.6997, mapUrl: 'https://maps.google.com/?q=Cherrapunji+Meghalaya' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Cherrapunji Waterfalls and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Cherrapunji Waterfalls Visit', desc: 'Full day exploring Cherrapunji Waterfalls with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 48,
  },
  {
    id: 'dawki-river',
    slug: 'dawki-river-highlight',
    title: 'Dawki River Discovery',
    destination: 'Dawki River - Dawki, Meghalaya',
    states: ['Meghalaya'],
    category: 'meghalaya',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('dawki-river') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('dawki-river'),
    description:
      'A crystal-clear river so transparent that boats appear to float in mid-air.',
    highlights: ['Dawki River', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["River", "Nature", "Photography"],
    location: { lat: 25.1826, lng: 92.0176, mapUrl: 'https://maps.google.com/?q=Dawki+Meghalaya' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Dawki River and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Dawki River Visit', desc: 'Full day exploring Dawki River with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 49,
  },
  {
    id: 'alleppey-backwaters',
    slug: 'alleppey-backwaters-highlight',
    title: 'Alleppey Backwaters Discovery',
    destination: 'Alleppey Backwaters - Alleppey, Kerala',
    states: ['Kerala'],
    category: 'kerala',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('alleppey-backwaters') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('alleppey-backwaters'),
    description:
      'Serene houseboat cruises through palm-fringed canals and paddy fields.',
    highlights: ['Alleppey Backwaters', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Backwaters", "Houseboat", "Relax"],
    location: { lat: 9.4981, lng: 76.3388, mapUrl: 'https://maps.google.com/?q=Alleppey+Kerala' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Alleppey Backwaters and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Alleppey Backwaters Visit', desc: 'Full day exploring Alleppey Backwaters with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 50,
  },
  {
    id: 'munnar-tea-gardens',
    slug: 'munnar-tea-gardens-highlight',
    title: 'Munnar Tea Gardens Discovery',
    destination: 'Munnar Tea Gardens - Munnar, Kerala',
    states: ['Kerala'],
    category: 'kerala',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('munnar-tea-gardens') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('munnar-tea-gardens'),
    description:
      'Misty hills carpeted with rolling tea plantations and cool mountain air.',
    highlights: ['Munnar Tea Gardens', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Tea", "Hills", "Nature"],
    location: { lat: 10.0889, lng: 77.0595, mapUrl: 'https://maps.google.com/?q=Munnar+Kerala' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Munnar Tea Gardens and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Munnar Tea Gardens Visit', desc: 'Full day exploring Munnar Tea Gardens with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 51,
  },
  {
    id: 'fort-kochi',
    slug: 'fort-kochi-highlight',
    title: 'Fort Kochi Discovery',
    destination: 'Fort Kochi - Kochi, Kerala',
    states: ['Kerala'],
    category: 'kerala',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('fort-kochi') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('fort-kochi'),
    description:
      'A historic port town with colonial architecture and iconic Chinese fishing nets.',
    highlights: ['Fort Kochi', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Heritage", "Culture", "Coastal"],
    location: { lat: 9.9658, lng: 76.2422, mapUrl: 'https://maps.google.com/?q=Kochi+Kerala' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Fort Kochi and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Fort Kochi Visit', desc: 'Full day exploring Fort Kochi with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 52,
  },
  {
    id: 'pashupatinath-temple',
    slug: 'pashupatinath-temple-highlight',
    title: 'Pashupatinath Temple Discovery',
    destination: 'Pashupatinath Temple - Kathmandu, Nepal',
    states: ['Kathmandu'],
    category: 'nepal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('pashupatinath-temple') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('pashupatinath-temple'),
    description:
      'A sacred Hindu temple complex on the banks of the Bagmati River.',
    highlights: ['Pashupatinath Temple', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Spiritual", "Heritage", "Culture"],
    location: { lat: 27.7106, lng: 85.3487, mapUrl: 'https://maps.google.com/?q=Kathmandu+Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Pashupatinath Temple and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Pashupatinath Temple Visit', desc: 'Full day exploring Pashupatinath Temple with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 53,
  },
  {
    id: 'phewa-lake',
    slug: 'phewa-lake-highlight',
    title: 'Phewa Lake Discovery',
    destination: 'Phewa Lake - Pokhara, Nepal',
    states: ['Pokhara'],
    category: 'nepal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('phewa-lake') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('phewa-lake'),
    description:
      'A tranquil lake mirroring the Annapurna range, ideal for boating at sunrise.',
    highlights: ['Phewa Lake', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Lakes", "Views", "Relax"],
    location: { lat: 28.2096, lng: 83.931, mapUrl: 'https://maps.google.com/?q=Pokhara+Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Phewa Lake and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Phewa Lake Visit', desc: 'Full day exploring Phewa Lake with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 54,
  },
  {
    id: 'lo-manthang',
    slug: 'lo-manthang-highlight',
    title: 'Lo Manthang Discovery',
    destination: 'Lo Manthang - Mustang, Nepal',
    states: ['Mustang'],
    category: 'nepal',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('lo-manthang') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('lo-manthang'),
    description:
      'A walled medieval city in the Himalayan rain-shadow desert, steeped in Tibetan culture.',
    highlights: ['Lo Manthang', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Culture", "Offbeat", "High Desert"],
    location: { lat: 29.1872, lng: 83.962, mapUrl: 'https://maps.google.com/?q=Mustang+Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Lo Manthang and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Lo Manthang Visit', desc: 'Full day exploring Lo Manthang with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 55,
  },
  {
    id: 'tigers-nest-monastery',
    slug: 'tigers-nest-monastery-highlight',
    title: 'Tiger’s Nest Monastery Discovery',
    destination: 'Tiger’s Nest Monastery - Paro, Bhutan',
    states: ['Paro'],
    category: 'bhutan',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('tigers-nest-monastery') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('tigers-nest-monastery'),
    description:
      'A cliffside monastery reached by a scenic hike, one of Bhutan’s most iconic sights.',
    highlights: ['Tiger’s Nest Monastery', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Monastery", "Trek", "Culture"],
    location: { lat: 27.4914, lng: 89.3633, mapUrl: 'https://maps.google.com/?q=Paro+Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Tiger’s Nest Monastery and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Tiger’s Nest Monastery Visit', desc: 'Full day exploring Tiger’s Nest Monastery with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 56,
  },
  {
    id: 'buddha-dordenma',
    slug: 'buddha-dordenma-highlight',
    title: 'Buddha Dordenma Discovery',
    destination: 'Buddha Dordenma - Thimphu, Bhutan',
    states: ['Thimphu'],
    category: 'bhutan',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('buddha-dordenma') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('buddha-dordenma'),
    description:
      'A giant golden Buddha statue overlooking the Thimphu valley.',
    highlights: ['Buddha Dordenma', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Culture", "Views", "Spiritual"],
    location: { lat: 27.4287, lng: 89.642, mapUrl: 'https://maps.google.com/?q=Thimphu+Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Buddha Dordenma and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Buddha Dordenma Visit', desc: 'Full day exploring Buddha Dordenma with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 57,
  },
  {
    id: 'punakha-dzong',
    slug: 'punakha-dzong-highlight',
    title: 'Punakha Dzong Discovery',
    destination: 'Punakha Dzong - Punakha, Bhutan',
    states: ['Punakha'],
    category: 'bhutan',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Highlight',
    badgeColor: 'teal',
    imageUrl: getPackageCover('punakha-dzong') || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: getPackageGallery('punakha-dzong'),
    description:
      'Bhutan’s most beautiful fortress, set at the confluence of two rivers.',
    highlights: ['Punakha Dzong', 'Local Sightseeing', 'Guided Visit', 'Photo Stops'],
    tags: ["Heritage", "Culture", "Riverside"],
    location: { lat: 27.5916, lng: 89.8775, mapUrl: 'https://maps.google.com/?q=Punakha+Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Check-in near Punakha Dzong and a relaxed evening to settle in.' },
      { day: 'Day 2', title: 'Punakha Dzong Visit', desc: 'Full day exploring Punakha Dzong with a local guide, with time for photos and leisure.' },
      { day: 'Day 3', title: 'Departure', desc: 'Breakfast and onward transfer.' },
    ],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Transfers', 'Local guide'],
    exclusions: ['Travel to/from the region', 'Lunch and dinner', 'Personal expenses', 'Entry fees where applicable'],
    isFeatured: false,
    isActive: true,
    sortOrder: 58,
  },
]

export const DESTINATIONS = [
  {
    id: 'ladakh', name: 'Ladakh', state: 'Ladakh', region: 'Ladakh', pkgCount: 9, imageUrl: ladakhImage, location: { mapUrl: 'https://maps.google.com/?q=Ladakh' },
    famousPlaces: [
      { name: 'Pangong Lake', desc: 'A high-altitude lake famous for its changing shades of blue.' },
      { name: 'Magnetic Hill', desc: 'A curious optical-illusion stretch where vehicles appear to defy gravity.' },
      { name: 'Thiksey Monastery', desc: 'A striking cliffside monastery resembling a mini Potala Palace.' },
    ],
  },
  {
    id: 'jammu-kashmir', name: 'Jammu & Kashmir', state: 'Jammu & Kashmir', region: 'Jammu & Kashmir', pkgCount: 9, imageUrl: jammuKashmirImage, location: { mapUrl: 'https://maps.google.com/?q=Jammu+and+Kashmir' },
    famousPlaces: [
      { name: 'Dal Lake', desc: 'Iconic shikara rides and houseboats on Srinagar\u2019s famous lake.' },
      { name: 'Gulmarg Gondola', desc: 'One of the world\u2019s highest cable cars, with meadow and snow views.' },
      { name: 'Mughal Gardens', desc: 'Terraced Mughal-era gardens overlooking Dal Lake.' },
    ],
  },
  {
    id: 'himachal', name: 'Himachal Pradesh', state: 'Himachal Pradesh', region: 'Himachal Pradesh', pkgCount: 10, imageUrl: himachalImage, location: { mapUrl: 'https://maps.google.com/?q=Himachal+Pradesh' },
    famousPlaces: [
      { name: 'Solang Valley', desc: 'Adventure sports and snow-capped views near Manali.' },
      { name: 'Old Manali', desc: 'Cafes, riverside lanes, and a laid-back mountain-town vibe.' },
      { name: 'Rohtang Pass', desc: 'A dramatic high-altitude pass with glaciers and panoramic views.' },
    ],
  },
  {
    id: 'uttarakhand', name: 'Uttarakhand', state: 'Uttarakhand', region: 'Uttarakhand', pkgCount: 10, imageUrl: uttarakhandImage, location: { mapUrl: 'https://maps.google.com/?q=Uttarakhand' },
    famousPlaces: [
      { name: 'Ganga Aarti, Rishikesh', desc: 'A mesmerizing riverside prayer ceremony at sunset.' },
      { name: 'Mussoorie Mall Road', desc: 'A charming hill-station promenade with viewpoints and cafes.' },
      { name: 'Valley of Flowers', desc: 'A UNESCO-listed alpine meadow bursting with seasonal blooms.' },
    ],
  },
  {
    id: 'darjeeling', name: 'Darjeeling', state: 'Darjeeling', region: 'West Bengal', pkgCount: 15, imageUrl: darjeelingImage, location: { mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' },
    famousPlaces: [
      { name: 'Tiger Hill', desc: 'Famous for sunrise views over Kanchenjunga.' },
      { name: 'Darjeeling Toy Train', desc: 'The UNESCO-listed narrow-gauge railway through the hills.' },
      { name: 'Tea Gardens', desc: 'Rolling estates producing some of the world\u2019s finest tea.' },
    ],
  },
  {
    id: 'sikkim', name: 'Sikkim', state: 'Sikkim', region: 'North-East India', pkgCount: 12, imageUrl: sikkimImage, location: { mapUrl: 'https://maps.google.com/?q=Sikkim' },
    famousPlaces: [
      { name: 'Tsomgo Lake', desc: 'A glacial lake at high altitude, often snow-fringed.' },
      { name: 'Rumtek Monastery', desc: 'One of Sikkim\u2019s largest and most significant monasteries.' },
      { name: 'Nathula Pass', desc: 'A historic Indo-China border pass on the old Silk Route.' },
    ],
  },
  {
    id: 'arunachal', name: 'Arunachal Pradesh', state: 'Arunachal Pradesh', region: 'Arunachal Pradesh', pkgCount: 8, imageUrl: arunachalImage, location: { mapUrl: 'https://maps.google.com/?q=Arunachal+Pradesh' },
    famousPlaces: [
      { name: 'Tawang Monastery', desc: 'India\u2019s largest monastery, perched above the Tawang valley.' },
      { name: 'Sela Pass', desc: 'A scenic high-altitude pass with a sacred lake nearby.' },
      { name: 'Ziro Valley', desc: 'A UNESCO-tentative valley known for its rice fields and Apatani culture.' },
    ],
  },
  {
    id: 'assam', name: 'Assam', state: 'Assam', region: 'Assam', pkgCount: 8, imageUrl: assamImage, location: { mapUrl: 'https://maps.google.com/?q=Assam' },
    famousPlaces: [
      { name: 'Kaziranga National Park', desc: 'Home to the one-horned rhinoceros and rich birdlife.' },
      { name: 'Kamakhya Temple', desc: 'A revered Shakti temple overlooking Guwahati.' },
      { name: 'Majuli Island', desc: 'The world\u2019s largest river island, known for its monasteries.' },
    ],
  },
  {
    id: 'meghalaya', name: 'Meghalaya', state: 'Meghalaya', region: 'Meghalaya', pkgCount: 8, imageUrl: meghalayaImage, location: { mapUrl: 'https://maps.google.com/?q=Meghalaya' },
    famousPlaces: [
      { name: 'Living Root Bridges', desc: 'Bridges grown from living tree roots over generations.' },
      { name: 'Cherrapunji Waterfalls', desc: 'Dramatic falls in one of the wettest places on Earth.' },
      { name: 'Dawki River', desc: 'A crystal-clear river famous for its glass-like clarity.' },
    ],
  },
  {
    id: 'kerala', name: 'Kerala', state: 'Kerala', region: 'Kerala', pkgCount: 11, imageUrl: keralaImage, location: { mapUrl: 'https://maps.google.com/?q=Kerala' },
    famousPlaces: [
      { name: 'Alleppey Backwaters', desc: 'Serene houseboat cruises through palm-fringed canals.' },
      { name: 'Munnar Tea Gardens', desc: 'Misty hills carpeted with rolling tea plantations.' },
      { name: 'Fort Kochi', desc: 'A historic port town with colonial architecture and Chinese fishing nets.' },
    ],
  },
  {
    id: 'nepal', name: 'Nepal', state: 'Nepal', region: 'Nepal', pkgCount: 6, imageUrl: nepalImage, location: { mapUrl: 'https://maps.google.com/?q=Nepal' },
    famousPlaces: [
      { name: 'Pashupatinath Temple', desc: 'A sacred Hindu temple complex on the Bagmati River.' },
      { name: 'Phewa Lake, Pokhara', desc: 'A tranquil lake with reflections of the Annapurna range.' },
      { name: 'Lo Manthang, Mustang', desc: 'A walled medieval city in the Himalayan rain-shadow desert.' },
    ],
  },
  {
    id: 'bhutan', name: 'Bhutan', state: 'Bhutan', region: 'Bhutan', pkgCount: 6, imageUrl: bhutanImage, location: { mapUrl: 'https://maps.google.com/?q=Bhutan' },
    famousPlaces: [
      { name: 'Tiger\u2019s Nest Monastery', desc: 'A cliffside monastery reached by a scenic hike above Paro.' },
      { name: 'Punakha Dzong', desc: 'Bhutan\u2019s most beautiful fortress, at the river confluence.' },
      { name: 'Buddha Dordenma', desc: 'A giant Buddha statue overlooking Thimphu valley.' },
    ],
  },
]

export const TESTIMONIALS = [
  { id: 1, authorName: 'Ananya Bose', authorFrom: 'Kolkata', tripName: 'Darjeeling Tour', rating: 5, reviewText: 'The sunrise at Tiger Hill left us speechless. Everything was coordinated beautifully and the trip felt effortless from start to finish.', avatarChar: 'A' },
  { id: 2, authorName: 'Rahul Mehta', authorFrom: 'Mumbai', tripName: 'Sikkim Family Tour', rating: 5, reviewText: 'The family trip exceeded expectations. Great pacing, very dependable transport, and genuine local knowledge throughout.', avatarChar: 'R' },
  { id: 3, authorName: 'Priya and Vikram', authorFrom: 'Delhi', tripName: 'Pelling Honeymoon', rating: 5, reviewText: 'The views, stays, and thoughtful planning made our honeymoon unforgettable. We felt taken care of the whole time.', avatarChar: 'P' },
  { id: 4, authorName: 'Suresh Nair', authorFrom: 'Bangalore', tripName: 'Dooars Wildlife Tour', rating: 5, reviewText: 'Saw rhinos, elephants, and so much birdlife. The team was professional, punctual, and easy to coordinate with.', avatarChar: 'S' },
  { id: 5, authorName: 'Karan Thakur', authorFrom: 'Pune', tripName: 'Sandakphu Trek', rating: 5, reviewText: 'One of the most rewarding treks I have done. The guide support and route planning were excellent.', avatarChar: 'K' },
]

export const CATEGORIES = [
  { id: 'all', label: 'All Packages', icon: 'All' },
  { id: 'darjeeling', label: 'Darjeeling', icon: 'Tea' },
  { id: 'sikkim', label: 'Sikkim', icon: 'Peak' },
  { id: 'dooars', label: 'Dooars', icon: 'Wild' },
  { id: 'kalimpong', label: 'Kalimpong', icon: 'Bloom' },
  { id: 'honeymoon', label: 'Honeymoon', icon: 'Love' },
  { id: 'trek', label: 'Treks', icon: 'Trail' },
  { id: 'combo', label: 'Combo Tours', icon: 'Mix' },
]
