import ladakhImage from '../assets/destinations/ladakh.svg'
import jammuKashmirImage from '../assets/destinations/jammu-kashmir.svg'
import himachalImage from '../assets/destinations/himachal.svg'
import uttarakhandImage from '../assets/destinations/uttarakhand.svg'
import darjeelingImage from '../assets/destinations/darjeeling.svg'
import sikkimImage from '../assets/destinations/sikkim.svg'
import arunachalImage from '../assets/destinations/arunachal.svg'
import assamImage from '../assets/destinations/assam.svg'
import meghalayaImage from '../assets/destinations/meghalaya.svg'
import keralaImage from '../assets/destinations/kerala.svg'
import nepalImage from '../assets/destinations/nepal.svg'
import bhutanImage from '../assets/destinations/bhutan.svg'

export const PACKAGES = [
  {
    id: 'classic-darjeeling',
    slug: 'classic-darjeeling-explorer',
    title: 'Classic Darjeeling Explorer',
    destination: 'Darjeeling, West Bengal',
    states: ['Darjeeling'],
    category: 'darjeeling',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Best Seller',
    badgeColor: 'red',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1570789210967-2cac24afeb00?w=800&q=80',
    ],
    description:
      "Experience the Queen of the Hills at its finest. Witness sunrise over Kanchenjunga from Tiger Hill, ride the UNESCO-listed Toy Train, and wander through aromatic tea estates.",
    highlights: ['Tiger Hill Sunrise', 'Darjeeling Toy Train', 'Tea Garden Walk', 'Batasia Loop', 'Himalayan Zoo'],
    tags: ['Nature', 'Heritage', 'Tea'],
    location: { lat: 27.036, lng: 88.2627, mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival and Mall Road', desc: 'Pickup from NJP or Bagdogra, scenic drive to Darjeeling, check-in, and evening at Chowrasta.' },
      { day: 'Day 2', title: 'Tiger Hill and Town', desc: 'Pre-dawn Tiger Hill visit, then Batasia Loop, Ghum Monastery, and the Himalayan Zoo.' },
      { day: 'Day 3', title: 'Tea Gardens and Culture', desc: 'Visit Happy Valley Tea Estate, the Tibetan Refugee Centre, and local shopping streets.' },
      { day: 'Day 4', title: 'Toy Train and Departure', desc: 'Toy Train joyride, breakfast, and transfer back to NJP.' },
    ],
    inclusions: ['3 nights hotel stay', 'Daily breakfast and dinner', 'All cab transfers', 'Tiger Hill jeep', 'Tea garden entry', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Personal expenses', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'gangtok-sikkim',
    slug: 'gangtok-rumtek-monastery',
    title: 'Gangtok and Rumtek Monastery',
    destination: 'Gangtok, Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Popular',
    badgeColor: 'blue',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80'],
    description:
      'Discover the lively capital of Sikkim, where ancient monasteries, markets, and Himalayan viewpoints come together in one memorable escape.',
    highlights: ['Rumtek Monastery', 'Gangtok Cable Car', 'MG Marg', 'Tashi Viewpoint', 'Banjhakri Falls'],
    tags: ['Spiritual', 'Nature', 'Culture'],
    location: { lat: 27.3389, lng: 88.6065, mapUrl: 'https://maps.google.com/?q=Gangtok,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Gangtok', desc: 'NJP pickup, scenic NH-10 drive, hotel check-in, and evening walk on MG Marg.' },
      { day: 'Day 2', title: 'Monasteries and Views', desc: 'Rumtek Monastery, Tashi Viewpoint, Banjhakri Falls, and the Institute of Tibetology.' },
      { day: 'Day 3', title: 'Cable Car and Markets', desc: 'Morning ropeway ride, Enchey Monastery visit, and shopping for local crafts.' },
      { day: 'Day 4', title: 'Departure', desc: 'Breakfast and transfer back to NJP.' },
    ],
    inclusions: ['3 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Cable car ticket', 'Local guide'],
    exclusions: ['Air or train tickets', 'Lunch', 'Entry fees', 'Personal shopping'],
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'grand-himalaya',
    slug: 'grand-eastern-himalaya-tour',
    title: 'Grand Eastern Himalaya Tour',
    destination: 'Darjeeling + Kalimpong + Sikkim',
    states: ['Darjeeling', 'Sikkim'],
    category: 'combo',
    nights: 6,
    days: 7,
    minPax: 2,
    badge: 'Best Value',
    badgeColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80'],
    description:
      'A week-long circuit through tea gardens, monasteries, mountain roads, and high-altitude lakes across the Eastern Himalayas.',
    highlights: ['Tea Gardens', 'Toy Train', 'Tsomgo Lake', 'Rumtek Monastery', 'Kalimpong Views'],
    tags: ['Multi-Destination', 'Heritage', 'Adventure'],
    location: { lat: 27.2, lng: 88.5, mapUrl: 'https://maps.google.com/?q=Darjeeling+Sikkim' },
    itinerary: [
      { day: 'Day 1-2', title: 'Darjeeling Highlights', desc: 'Tiger Hill sunrise, tea garden walk, and Toy Train joyride.' },
      { day: 'Day 3', title: 'Kalimpong', desc: 'Zong Dog Palri Monastery, Deolo Hill, and flower nurseries.' },
      { day: 'Day 4-5', title: 'Gangtok', desc: 'Rumtek, Tashi Viewpoint, cable car ride, and MG Marg.' },
      { day: 'Day 6', title: 'Tsomgo Lake', desc: 'Day trip to the high-altitude lake with permits arranged.' },
      { day: 'Day 7', title: 'Departure', desc: 'Return to NJP.' },
    ],
    inclusions: ['6 nights accommodation', 'Daily breakfast and dinner', 'All transfers', 'Permits', 'Sightseeing', 'Guide'],
    exclusions: ['Flights or trains', 'Lunch', 'Optional rides', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'dooars-wildlife',
    slug: 'dooars-wild-jungle-safari',
    title: 'Dooars Wild Jungle Safari',
    destination: 'Dooars, West Bengal',
    states: ['Darjeeling'],
    category: 'dooars',
    nights: 3,
    days: 4,
    minPax: 4,
    badge: 'Wildlife',
    badgeColor: 'green',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80'],
    description:
      'Explore the forests of North Bengal with jeep safaris, birdwatching, and chances to spot rhinos, elephants, and gaur.',
    highlights: ['Rhino Safari', 'Elephant Safari', 'Gorumara', 'Jaldapara', 'Chilapata Forest'],
    tags: ['Wildlife', 'Nature', 'Safari'],
    location: { lat: 26.75, lng: 89.16, mapUrl: 'https://maps.google.com/?q=Dooars,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Siliguri to Dooars', desc: 'Transfer to eco-resort and evening nature walk.' },
      { day: 'Day 2', title: 'Gorumara Safari', desc: 'Morning jeep safari and sunset watchtower visit.' },
      { day: 'Day 3', title: 'Jaldapara', desc: 'Elephant safari and wildlife spotting.' },
      { day: 'Day 4', title: 'Departure', desc: 'Forest drive and return to NJP.' },
    ],
    inclusions: ['3 nights resort stay', 'Safaris', 'Park permits', 'Naturalist guide'],
    exclusions: ['Air or train tickets', 'Alcohol', 'Tips', 'Camera fees'],
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'pelling-honeymoon',
    slug: 'pelling-romantic-getaway',
    title: 'Pelling Romantic Getaway',
    destination: 'Pelling, West Sikkim',
    states: ['Sikkim'],
    category: 'honeymoon',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Honeymoon',
    badgeColor: 'pink',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    description:
      'A romantic mountain retreat with sweeping Kanchenjunga views, monasteries, waterfalls, and special honeymoon touches.',
    highlights: ['View Room', 'Glass Skywalk', 'Pemayangtse Monastery', 'Waterfalls', 'Candlelight Dinner'],
    tags: ['Romantic', 'Mountains', 'Honeymoon'],
    location: { lat: 27.35, lng: 88.2167, mapUrl: 'https://maps.google.com/?q=Pelling,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Pickup, transfer to Pelling, and welcome dinner.' },
      { day: 'Day 2', title: 'Monastery Trail', desc: 'Pemayangtse Monastery, Rabdentse ruins, and heritage viewpoints.' },
      { day: 'Day 3', title: 'Skywalk and Waterfalls', desc: 'Glass sky bridge and waterfall excursion.' },
      { day: 'Day 4', title: 'Lake and Leisure', desc: 'Khecheopalri Lake visit and relaxed afternoon.' },
      { day: 'Day 5', title: 'Departure', desc: 'Breakfast and transfer back.' },
    ],
    inclusions: ['4 nights resort stay', 'Daily breakfast and dinner', 'Special honeymoon arrangements', 'Transfers'],
    exclusions: ['Air or train tickets', 'Lunch', 'Extra spa sessions', 'Alcohol'],
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'kalimpong',
    slug: 'kalimpong-flower-valley',
    title: 'Kalimpong Flower Valley',
    destination: 'Kalimpong, West Bengal',
    states: ['Darjeeling'],
    category: 'kalimpong',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Hidden Gem',
    badgeColor: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    gallery: [],
    description:
      'A compact hill retreat known for nurseries, monasteries, Teesta valley viewpoints, and a quieter pace than the busier hill stations.',
    highlights: ['Flower Nurseries', 'Deolo Hill', 'Monasteries', 'Teesta Views', 'Arts and Crafts'],
    tags: ['Nature', 'Culture', 'Offbeat'],
    location: { lat: 27.066, lng: 88.468, mapUrl: 'https://maps.google.com/?q=Kalimpong,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Transfer from NJP and local market stroll.' },
      { day: 'Day 2', title: 'Views and Monasteries', desc: 'Deolo Hill, monasteries, and nursery visits.' },
      { day: 'Day 3', title: 'Departure', desc: 'Arts and crafts centre visit before return.' },
    ],
    inclusions: ['2 nights hotel stay', 'Daily breakfast', 'Transfers', 'Guide'],
    exclusions: ['Air or train tickets', 'Some meals', 'Entry fees'],
    isFeatured: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'sandakphu-trek',
    slug: 'sandakphu-trek',
    title: 'Sandakphu Summit Trek',
    destination: 'Sandakphu, West Bengal',
    states: ['Darjeeling'],
    category: 'trek',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Adventure',
    badgeColor: 'orange',
    imageUrl: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80'],
    description:
      "A bucket-list trek with ridgeline views of Everest, Kanchenjunga, Lhotse, and Makalu on clear mornings.",
    highlights: ['High-altitude views', 'Singalila trails', 'Tumling', 'Kalapokhri', 'Summit sunrise'],
    tags: ['Trek', 'Adventure', 'Summit'],
    location: { lat: 27.1054, lng: 87.848, mapUrl: 'https://maps.google.com/?q=Sandakphu,West+Bengal' },
    itinerary: [
      { day: 'Day 1', title: 'Maneybhanjang to Tumling', desc: 'Trek through Singalila National Park.' },
      { day: 'Day 2', title: 'Tumling to Kalapokhri', desc: 'Ridge walk with Himalayan views.' },
      { day: 'Day 3', title: 'Summit Day', desc: 'Climb to Sandakphu and watch the sunrise panorama.' },
      { day: 'Day 4', title: 'Descent', desc: 'Forest descent and overnight stay.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to base and transfer to Siliguri.' },
    ],
    inclusions: ['Stay on trek', 'Meals on trek', 'Guide', 'Porter', 'Permits', 'First aid'],
    exclusions: ['Transport to Siliguri', 'Gear rental', 'Insurance'],
    isFeatured: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'lachung-yumthang',
    slug: 'lachung-yumthang-valley',
    title: 'Lachung and Yumthang Valley',
    destination: 'North Sikkim',
    states: ['Sikkim'],
    category: 'sikkim',
    nights: 4,
    days: 5,
    minPax: 4,
    badge: 'Seasonal',
    badgeColor: 'teal',
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    gallery: [],
    description:
      'A scenic North Sikkim journey through alpine valleys, rivers, seasonal flowers, and mountain villages.',
    highlights: ['Yumthang Valley', 'Zero Point', 'Lachung Village', 'Rhododendrons', 'Glacial streams'],
    tags: ['Valley', 'Flowers', 'North Sikkim'],
    location: { lat: 27.8167, lng: 88.7167, mapUrl: 'https://maps.google.com/?q=Yumthang+Valley,Sikkim' },
    itinerary: [
      { day: 'Day 1', title: 'Gangtok to Lachung', desc: 'Drive through river valleys and mountain roads.' },
      { day: 'Day 2', title: 'Yumthang and Zero Point', desc: 'Visit the valley and optional Zero Point excursion.' },
      { day: 'Day 3', title: 'Village Exploration', desc: 'Discover local culture and monastery life.' },
      { day: 'Day 4', title: 'Return to Gangtok', desc: 'Scenic drive back.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer toward NJP or Siliguri.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast and dinner', 'Permits', 'Transfers', 'Guide'],
    exclusions: ['Optional excursions', 'Lunch', 'Personal expenses', 'Insurance'],
    isFeatured: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'leh-ladakh-highlights',
    slug: 'leh-ladakh-highlights',
    title: 'Leh Ladakh Highlights',
    destination: 'Leh, Nubra, Pangong - Ladakh',
    states: ['Ladakh'],
    category: 'ladakh',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Top Pick',
    badgeColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80'],
    description:
      'A classic Ladakh circuit covering high passes, monasteries, Nubra dunes, and the stunning blue waters of Pangong.',
    highlights: ['Khardung La', 'Nubra Valley', 'Pangong Lake', 'Shanti Stupa', 'Monasteries'],
    tags: ['Mountains', 'Adventure', 'Road Trip'],
    location: { lat: 34.1526, lng: 77.577, mapUrl: 'https://maps.google.com/?q=Leh,Ladakh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Leh', desc: 'Hotel check-in and easy acclimatization day.' },
      { day: 'Day 2', title: 'Leh Local Sightseeing', desc: 'Shanti Stupa, Palace area, and market stroll.' },
      { day: 'Day 3', title: 'Nubra Valley', desc: 'Drive via Khardung La and enjoy the valley landscapes.' },
      { day: 'Day 4', title: 'Pangong Lake', desc: 'High-altitude drive to the iconic lake.' },
      { day: 'Day 5', title: 'Monasteries Route', desc: 'Scenic monasteries and river confluence viewpoints.' },
      { day: 'Day 6', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing', 'Permits'],
    exclusions: ['Flights', 'Lunch and dinner', 'Personal expenses', 'Optional activities'],
    isFeatured: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'kashmir-gulmarg-pahalgam',
    slug: 'kashmir-gulmarg-pahalgam',
    title: 'Kashmir Valley Escape',
    destination: 'Srinagar, Gulmarg, Pahalgam - Jammu & Kashmir',
    states: ['Jammu & Kashmir'],
    category: 'kashmir',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Popular',
    badgeColor: 'blue',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'Dal Lake serenity, Mughal gardens, and scenic day trips to Gulmarg and Pahalgam for a relaxed mountain holiday.',
    highlights: ['Dal Lake Shikara', 'Gulmarg Meadows', 'Pahalgam Valley', 'Mughal Gardens'],
    tags: ['Nature', 'Valleys', 'Relax'],
    location: { lat: 34.0837, lng: 74.7973, mapUrl: 'https://maps.google.com/?q=Srinagar,Jammu+and+Kashmir' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Srinagar', desc: 'Check-in and evening Dal Lake experience.' },
      { day: 'Day 2', title: 'Srinagar Gardens', desc: 'Mughal gardens and local markets.' },
      { day: 'Day 3', title: 'Gulmarg Day Trip', desc: 'Meadows and optional gondola ride.' },
      { day: 'Day 4', title: 'Pahalgam Day Trip', desc: 'Valley views and river-side time.' },
      { day: 'Day 5', title: 'Leisure Day', desc: 'Flexible day for shopping and experiences.' },
      { day: 'Day 6', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional rides'],
    isFeatured: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'himachal-manali-kasol',
    slug: 'himachal-manali-kasol',
    title: 'Manali and Kasol Getaway',
    destination: 'Manali, Solang, Kasol - Himachal Pradesh',
    states: ['Himachal Pradesh'],
    category: 'himachal',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Best Seller',
    badgeColor: 'red',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'A crowd-favorite Himachal route with mountain views, cafes, and adventure options around Solang and nearby valleys.',
    highlights: ['Solang Valley', 'Old Manali', 'Parvati Valley', 'Cafe Hopping'],
    tags: ['Mountains', 'Leisure', 'Adventure'],
    location: { lat: 32.2396, lng: 77.1887, mapUrl: 'https://maps.google.com/?q=Manali,Himachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Manali', desc: 'Hotel check-in and local walk.' },
      { day: 'Day 2', title: 'Solang and Views', desc: 'Solang Valley activities and viewpoints.' },
      { day: 'Day 3', title: 'Kasol Transfer', desc: 'Drive to Kasol, riverside evening.' },
      { day: 'Day 4', title: 'Parvati Valley', desc: 'Explore nearby spots and cafes.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'All transfers', 'Sightseeing'],
    exclusions: ['Transport to Himachal', 'Adventure activities', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 'uttarakhand-rishikesh-mussoorie',
    slug: 'uttarakhand-rishikesh-mussoorie',
    title: 'Rishikesh and Mussoorie Retreat',
    destination: 'Rishikesh, Mussoorie - Uttarakhand',
    states: ['Uttarakhand'],
    category: 'uttarakhand',
    nights: 3,
    days: 4,
    minPax: 2,
    badge: 'Relax',
    badgeColor: 'teal',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80'],
    description:
      'A balanced Uttarakhand trip combining the calm of Rishikesh with the viewpoints and mall-road charm of Mussoorie.',
    highlights: ['Ganga Aarti', 'River Views', 'Mussoorie Viewpoints', 'Local Markets'],
    tags: ['Relax', 'Nature', 'Spiritual'],
    location: { lat: 30.0869, lng: 78.2676, mapUrl: 'https://maps.google.com/?q=Rishikesh,Uttarakhand' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Rishikesh', desc: 'Check-in and evening aarti.' },
      { day: 'Day 2', title: 'Rishikesh Sightseeing', desc: 'Ghats and viewpoints at your pace.' },
      { day: 'Day 3', title: 'Mussoorie', desc: 'Drive to Mussoorie and explore the town.' },
      { day: 'Day 4', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Transport to Uttarakhand', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 'arunachal-tawang-monasteries',
    slug: 'arunachal-tawang-monasteries',
    title: 'Tawang Monasteries and Lakes',
    destination: 'Tawang - Arunachal Pradesh',
    states: ['Arunachal Pradesh'],
    category: 'arunachal',
    nights: 5,
    days: 6,
    minPax: 2,
    badge: 'Offbeat',
    badgeColor: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80'],
    description:
      'A scenic Arunachal journey focused on Tawang’s monasteries, mountain passes, and high-altitude lakes.',
    highlights: ['Tawang Monastery', 'Sela Pass', 'High-Altitude Lakes', 'Local Culture'],
    tags: ['Offbeat', 'Mountains', 'Culture'],
    location: { lat: 27.5864, lng: 91.8597, mapUrl: 'https://maps.google.com/?q=Tawang,Arunachal+Pradesh' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival and Transfer', desc: 'Begin the mountain route and settle in.' },
      { day: 'Day 2', title: 'Pass and Views', desc: 'Sela Pass and lake stops.' },
      { day: 'Day 3', title: 'Monastery Day', desc: 'Explore the monastery and viewpoints.' },
      { day: 'Day 4', title: 'Local Experiences', desc: 'Markets and cultural stops.' },
      { day: 'Day 5', title: 'Leisure / Buffer', desc: 'Flexible day for weather and permits.' },
      { day: 'Day 6', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Permits assistance'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 'assam-kaziranga-wildlife',
    slug: 'assam-kaziranga-wildlife',
    title: 'Kaziranga Wildlife Safari',
    destination: 'Kaziranga - Assam',
    states: ['Assam'],
    category: 'assam',
    nights: 2,
    days: 3,
    minPax: 2,
    badge: 'Wildlife',
    badgeColor: 'green',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80'],
    description:
      'A short and powerful wildlife break in Kaziranga, home to the one-horned rhinoceros and rich birdlife.',
    highlights: ['Jeep Safari', 'Rhino Spotting', 'Birding', 'Nature Trails'],
    tags: ['Wildlife', 'Nature', 'Safari'],
    location: { lat: 26.5775, lng: 93.1711, mapUrl: 'https://maps.google.com/?q=Kaziranga,Assam' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival', desc: 'Resort check-in and evening nature walk.' },
      { day: 'Day 2', title: 'Safari Day', desc: 'Jeep safari and local experiences.' },
      { day: 'Day 3', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Safari assistance'],
    exclusions: ['Transport to Assam', 'Safari tickets', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 'meghalaya-shillong-cherrapunji',
    slug: 'meghalaya-shillong-cherrapunji',
    title: 'Meghalaya Waterfalls and Caves',
    destination: 'Shillong, Cherrapunji, Dawki - Meghalaya',
    states: ['Meghalaya'],
    category: 'meghalaya',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Trending',
    badgeColor: 'orange',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'],
    description:
      'Blue rivers, misty waterfalls, limestone caves, and viewpoints across Meghalaya’s most loved circuit.',
    highlights: ['Dawki River', 'Cherrapunji Falls', 'Caves', 'Viewpoints'],
    tags: ['Nature', 'Waterfalls', 'Road Trip'],
    location: { lat: 25.5788, lng: 91.8933, mapUrl: 'https://maps.google.com/?q=Shillong,Meghalaya' },
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Shillong', desc: 'Check-in and local evening.' },
      { day: 'Day 2', title: 'Cherrapunji', desc: 'Waterfalls and viewpoints.' },
      { day: 'Day 3', title: 'Caves and Trails', desc: 'Cave visit and scenic drives.' },
      { day: 'Day 4', title: 'Dawki Day', desc: 'Crystal-clear river experience.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return journey.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Transport to Meghalaya', 'Entry fees', 'Personal expenses'],
    isFeatured: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 'kerala-backwaters-munnar',
    slug: 'kerala-backwaters-munnar',
    title: 'Kerala Backwaters and Tea Hills',
    destination: 'Munnar, Alleppey, Kochi - Kerala',
    states: ['Kerala'],
    category: 'kerala',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'Family',
    badgeColor: 'blue',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'],
    description:
      'A classic Kerala mix of hill-station tea gardens, backwater calm, and city highlights for a smooth vacation.',
    highlights: ['Munnar Tea Gardens', 'Backwaters', 'Houseboat Experience', 'Kochi'],
    tags: ['Relax', 'Nature', 'Family'],
    location: { lat: 9.9312, lng: 76.2673, mapUrl: 'https://maps.google.com/?q=Kochi,Kerala' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Kochi', desc: 'Check-in and local sightseeing.' },
      { day: 'Day 2', title: 'Munnar', desc: 'Drive to Munnar and explore tea hills.' },
      { day: 'Day 3', title: 'Munnar Sightseeing', desc: 'Viewpoints and gardens.' },
      { day: 'Day 4', title: 'Backwaters', desc: 'Transfer to Alleppey for backwaters.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to Kochi and depart.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Entry fees', 'Personal expenses', 'Optional experiences'],
    isFeatured: true,
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 'nepal-kathmandu-pokhara',
    slug: 'nepal-kathmandu-pokhara',
    title: 'Kathmandu and Pokhara Explorer',
    destination: 'Kathmandu, Pokhara - Nepal',
    states: ['Nepal'],
    category: 'nepal',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'International',
    badgeColor: 'teal',
    imageUrl: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'],
    description:
      'Temples, lakeside calm, and Himalayan views across Nepal’s most loved duo: Kathmandu and Pokhara.',
    highlights: ['Kathmandu Temples', 'Pokhara Lakeside', 'Sunrise Viewpoint', 'Local Markets'],
    tags: ['Culture', 'Views', 'International'],
    location: { lat: 27.7172, lng: 85.324, mapUrl: 'https://maps.google.com/?q=Kathmandu,Nepal' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Kathmandu', desc: 'Check-in and local evening.' },
      { day: 'Day 2', title: 'Heritage Tour', desc: 'Temples and heritage squares.' },
      { day: 'Day 3', title: 'Pokhara Transfer', desc: 'Drive/flight to Pokhara and relax lakeside.' },
      { day: 'Day 4', title: 'Pokhara Views', desc: 'Sunrise viewpoint and sightseeing.' },
      { day: 'Day 5', title: 'Departure', desc: 'Return to Kathmandu and depart.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['International flights', 'Visa fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 'bhutan-paro-thimphu',
    slug: 'bhutan-paro-thimphu',
    title: 'Bhutan Paro and Thimphu Journey',
    destination: 'Paro, Thimphu - Bhutan',
    states: ['Bhutan'],
    category: 'bhutan',
    nights: 4,
    days: 5,
    minPax: 2,
    badge: 'International',
    badgeColor: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'],
    description:
      'A gentle introduction to Bhutan’s calm capital and Paro valley, with cultural sights and scenic mountain drives.',
    highlights: ['Paro Valley', 'Thimphu Culture', 'Scenic Drives', 'Monasteries'],
    tags: ['Culture', 'International', 'Peaceful'],
    location: { lat: 27.4728, lng: 89.639, mapUrl: 'https://maps.google.com/?q=Thimphu,Bhutan' },
    itinerary: [
      { day: 'Day 1', title: 'Arrive Paro', desc: 'Check-in and local sightseeing.' },
      { day: 'Day 2', title: 'Thimphu', desc: 'Drive to Thimphu and explore the city.' },
      { day: 'Day 3', title: 'Culture Day', desc: 'Monasteries, markets, and viewpoints.' },
      { day: 'Day 4', title: 'Back to Paro', desc: 'Return to Paro valley and leisure time.' },
      { day: 'Day 5', title: 'Departure', desc: 'Airport transfer.' },
    ],
    inclusions: ['Accommodation', 'Daily breakfast', 'Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Visa/permit fees', 'Personal expenses', 'Optional activities'],
    isFeatured: false,
    isActive: true,
    sortOrder: 18,
  },
]

export const DESTINATIONS = [
  { id: 'ladakh', name: 'Ladakh', state: 'Ladakh', region: 'Ladakh', pkgCount: 6, imageUrl: ladakhImage, location: { mapUrl: 'https://maps.google.com/?q=Ladakh' } },
  { id: 'jammu-kashmir', name: 'Jammu & Kashmir', state: 'Jammu & Kashmir', region: 'Jammu & Kashmir', pkgCount: 6, imageUrl: jammuKashmirImage, location: { mapUrl: 'https://maps.google.com/?q=Jammu+and+Kashmir' } },
  { id: 'himachal', name: 'Himachal Pradesh', state: 'Himachal Pradesh', region: 'Himachal Pradesh', pkgCount: 7, imageUrl: himachalImage, location: { mapUrl: 'https://maps.google.com/?q=Himachal+Pradesh' } },
  { id: 'uttarakhand', name: 'Uttarakhand', state: 'Uttarakhand', region: 'Uttarakhand', pkgCount: 7, imageUrl: uttarakhandImage, location: { mapUrl: 'https://maps.google.com/?q=Uttarakhand' } },
  { id: 'darjeeling', name: 'Darjeeling', state: 'Darjeeling', region: 'West Bengal', pkgCount: 12, imageUrl: darjeelingImage, location: { mapUrl: 'https://maps.google.com/?q=Darjeeling,West+Bengal' } },
  { id: 'sikkim', name: 'Sikkim', state: 'Sikkim', region: 'North-East India', pkgCount: 9, imageUrl: sikkimImage, location: { mapUrl: 'https://maps.google.com/?q=Sikkim' } },
  { id: 'arunachal', name: 'Arunachal Pradesh', state: 'Arunachal Pradesh', region: 'Arunachal Pradesh', pkgCount: 5, imageUrl: arunachalImage, location: { mapUrl: 'https://maps.google.com/?q=Arunachal+Pradesh' } },
  { id: 'assam', name: 'Assam', state: 'Assam', region: 'Assam', pkgCount: 5, imageUrl: assamImage, location: { mapUrl: 'https://maps.google.com/?q=Assam' } },
  { id: 'meghalaya', name: 'Meghalaya', state: 'Meghalaya', region: 'Meghalaya', pkgCount: 5, imageUrl: meghalayaImage, location: { mapUrl: 'https://maps.google.com/?q=Meghalaya' } },
  { id: 'kerala', name: 'Kerala', state: 'Kerala', region: 'Kerala', pkgCount: 8, imageUrl: keralaImage, location: { mapUrl: 'https://maps.google.com/?q=Kerala' } },
  { id: 'nepal', name: 'Nepal', state: 'Nepal', region: 'Nepal', pkgCount: 6, imageUrl: nepalImage, location: { mapUrl: 'https://maps.google.com/?q=Nepal' } },
  { id: 'bhutan', name: 'Bhutan', state: 'Bhutan', region: 'Bhutan', pkgCount: 6, imageUrl: bhutanImage, location: { mapUrl: 'https://maps.google.com/?q=Bhutan' } },
]

export const TESTIMONIALS = [
  { id: 1, authorName: 'Ananya Bose', authorFrom: 'Kolkata', tripName: 'Darjeeling Tour', rating: 5, reviewText: 'The sunrise at Tiger Hill left us speechless. Everything was coordinated beautifully and the trip felt effortless from start to finish.', avatarChar: 'A' },
  { id: 2, authorName: 'Rahul Mehta', authorFrom: 'Mumbai', tripName: 'Sikkim Family Tour', rating: 5, reviewText: 'The family trip exceeded expectations. Great pacing, very dependable transport, and genuine local knowledge throughout.', avatarChar: 'R' },
  { id: 3, authorName: 'Priya and Vikram', authorFrom: 'Delhi', tripName: 'Pelling Honeymoon', rating: 5, reviewText: 'The views, stays, and thoughtful planning made our honeymoon unforgettable. We felt taken care of the whole time.', avatarChar: 'P' },
  { id: 4, authorName: 'Suresh Nair', authorFrom: 'Bangalore', tripName: 'Dooars Wildlife Tour', rating: 5, reviewText: 'Saw rhinos, elephants, and so much birdlife. The team was professional, punctual, and easy to coordinate with.', avatarChar: 'S' },
  { id: 5, authorName: 'Karan Thakur', authorFrom: 'Pune', tripName: 'Sandakphu Trek', rating: 5, reviewText: 'One of the most rewarding treks I have done. The guide support and route planning were excellent.', avatarChar: 'K' },
]

export const CATEGORIES = [
  { id: 'all', label: 'All Packages', icon: 'All' },
  { id: 'darjeeling', label: 'Darjeeling', icon: 'Tea' },
  { id: 'sikkim', label: 'Sikkim', icon: 'Peak' },
  { id: 'dooars', label: 'Dooars', icon: 'Wild' },
  { id: 'kalimpong', label: 'Kalimpong', icon: 'Bloom' },
  { id: 'honeymoon', label: 'Honeymoon', icon: 'Love' },
  { id: 'trek', label: 'Treks', icon: 'Trail' },
  { id: 'combo', label: 'Combo Tours', icon: 'Mix' },
]
